// Planner static data — ported from goals-tracker App.jsx
// All schedule data for Feb 27 – Mar 31, 2026

export type CatKey =
  | 'sleep' | 'fitness' | 'recovery' | 'job' | 'heloc'
  | 'legal' | 'health' | 'admin' | 'wellness' | 'personal' | 'tax'

export interface CatConfig {
  label: string
  icon: string
}

export interface DayBlock {
  t: string
  cat: CatKey
  task: string
}

export interface Day {
  date: string
  week: number
  tag: string
  theme: string
  blocks: DayBlock[]
}

export interface SleepRule {
  icon: string
  rule: string
}

export interface WeeklyRow {
  d: string
  am: string
  pm: string
}

export interface RecoveryItem {
  icon: string
  title: string
  desc: string
}

export interface ClassPassItem {
  type: string
  studios: string
}

export interface ChecklistItem {
  c: CatKey
  t: string
}

// ── Category config ────────────────────────────────────────

export const CAT: Record<CatKey, CatConfig> = {
  sleep:    { label: 'Sleep',            icon: '🌙' },
  fitness:  { label: 'Fitness',          icon: '💪' },
  recovery: { label: 'Recovery',         icon: '🧊' },
  job:      { label: 'Job Search',       icon: '🎯' },
  heloc:    { label: 'HELOC',            icon: '🏠' },
  legal:    { label: 'Legal/BoA',        icon: '⚖️' },
  health:   { label: 'Health/Benefits',  icon: '🩺' },
  admin:    { label: 'Admin/Claims',     icon: '📋' },
  wellness: { label: 'Wellness',         icon: '🧘' },
  personal: { label: 'Personal',         icon: '☀️' },
  tax:      { label: 'Tax/IRS',          icon: '🧾' },
}

export const CC: Record<CatKey, string> = {
  sleep:    '#818cf8',
  fitness:  '#34d399',
  recovery: '#67e8f9',
  job:      '#fbbf24',
  heloc:    '#f87171',
  legal:    '#fb923c',
  health:   '#22d3ee',
  admin:    '#f472b6',
  wellness: '#a78bfa',
  personal: '#a1a1aa',
  tax:      '#e879f9',
}

// ── 33-day schedule ────────────────────────────────────────

export const DAYS: Day[] = [
  // ═══════════════════════════════════════════
  // WEEK 1 — THIS WEEK (Feb 27 – Mar 2)
  // ═══════════════════════════════════════════
  {
    date: 'Fri, Feb 27', week: 1, tag: 'Light Day — Interviews + Workout',
    theme: 'Keep it light. Gym, Goldman Sachs & RealPage interviews, walk, TRT regime starts.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Full body — compound lifts, moderate weight (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'job',      task: 'Interview prep — review Goldman Sachs & RealPage roles, talking points' },
      { t: '11:00',   cat: 'job',      task: '📞 Interview: Goldman Sachs' },
      { t: '12:00',   cat: 'personal', task: 'Lunch + decompress between interviews' },
      { t: '1:00 PM', cat: 'job',      task: '📞 Interview: RealPage' },
      { t: '2:00',    cat: 'personal', task: 'Post-interview notes — capture key takeaways, follow-up items' },
      { t: '3:00',    cat: 'fitness',  task: 'Outdoor walk (30-45 min) — clear head, fresh air' },
      { t: '4:00',    cat: 'health',   task: '💉 TRT: Note — hCG + Anastrozole 1 mg done yesterday (Thu Feb 26). Next: hCG Sun Mar 1' },
      { t: '4:30',    cat: 'personal', task: 'Free time — keep it light' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Free time — relax, reward yourself' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down (Fri flex)' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Sat, Feb 28', week: 1, tag: 'Recovery Day',
    theme: 'Massage + IR sauna. House + meal prep. Social.',
    blocks: [
      { t: '8:00 AM', cat: 'sleep',    task: 'Wake up naturally (by 8:00)' },
      { t: '8:15',    cat: 'wellness', task: 'Meditation + gratitude journal' },
      { t: '8:30',    cat: 'recovery', task: 'Extended stretch (20-30 min) — foam rolling, deep mobility' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast + coffee' },
      { t: '10:00',   cat: 'recovery', task: '💆 Massage (60-90 min)' },
      { t: '11:30',   cat: 'fitness',  task: 'Outdoor: cycling, hike, or long walk (60-90 min)' },
      { t: '1:00 PM', cat: 'personal', task: 'Lunch' },
      { t: '1:45',    cat: 'personal', task: 'House: clean, laundry, organize' },
      { t: '3:15',    cat: 'personal', task: 'Grocery shopping + meal prep' },
      { t: '5:00',    cat: 'recovery', task: '🧖 IR sauna (30-45 min)' },
      { t: '6:00',    cat: 'personal', task: 'Free time — hobbies, Legos, camera, cooking' },
      { t: '7:30',    cat: 'personal', task: 'Social: dinner out, friends, date' },
      { t: '10:30',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Sun, Mar 1', week: 1, tag: 'Week Review + Plan',
    theme: 'Review progress. Plan ahead. TRT: hCG today.',
    blocks: [
      { t: '8:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '8:15',    cat: 'wellness', task: 'Meditation + gratitude journal' },
      { t: '8:30',    cat: 'recovery', task: 'Extended stretch (20-30 min) — yoga flow' },
      { t: '9:00',    cat: 'health',   task: '💉 TRT: hCG injection' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'personal', task: 'Weekly planning: Review what got done, set priorities for the week' },
      { t: '11:00',   cat: 'job',      task: 'Full pipeline review — adjust strategy based on data so far' },
      { t: '12:00',   cat: 'personal', task: 'Lunch' },
      { t: '12:45',   cat: 'heloc',    task: 'HELOC: Final assessment — close or abandon stragglers' },
      { t: '1:30',    cat: 'legal',    task: 'BoA: Attorney status + CFPB rebuttal finalization' },
      { t: '2:30',    cat: 'recovery', task: '💆 Optional 2nd massage (or rest)' },
      { t: '4:00',    cat: 'fitness',  task: 'Gym: Upper body (60 min)' },
      { t: '5:15',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Free time — prep for the week' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Mon, Mar 2', week: 1, tag: 'Job Search Acceleration',
    theme: 'Ramp job search to max. 17 days to March 19. TRT: Testosterone injection today.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '7:45',    cat: 'health',   task: '💉 TRT: Testosterone injection (Week 1)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Heavy legs — squats, deadlifts, hip thrusts (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'job',      task: 'Deep work: Apply to 5+ roles. Expand targets if needed' },
      { t: '12:00',   cat: 'job',      task: 'Cold outreach: 5 hiring managers or VPs at new target companies' },
      { t: '12:45',   cat: 'personal', task: 'Lunch' },
      { t: '1:30',    cat: 'job',      task: 'LinkedIn: New thought leadership post + engage with 10 posts' },
      { t: '2:30',    cat: 'job',      task: 'Follow up on ALL pending recruiter conversations' },
      { t: '3:15',    cat: 'heloc',    task: 'HELOC: Final push — where are we? Decision needed' },
      { t: '4:00',    cat: 'fitness',  task: 'Outdoor walk (30-45 min)' },
      { t: '5:00',    cat: 'personal', task: 'Free time' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'legal',    task: 'BoA: Next steps with engaged attorney or expand search' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  // ═══════════════════════════════════════════
  // WEEK 2 — SPRINT TO DEADLINE (Mar 3–9)
  // ═══════════════════════════════════════════
  {
    date: 'Tue, Mar 3', week: 2, tag: 'Benefits Final Push',
    theme: 'Last big benefits sweep. Evening yoga.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Heavy push — bench, OHP, incline DB (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'health',   task: 'Benefits final push: Confirm all medical appts before March 19' },
      { t: '10:45',   cat: 'health',   task: 'MRA/FSA: Spend remaining balances on eligible items' },
      { t: '11:30',   cat: 'health',   task: 'Hyatt Legal Plan: Final consult if not done' },
      { t: '12:15',   cat: 'personal', task: 'Lunch' },
      { t: '1:00 PM', cat: 'job',      task: 'Apply to 3-5 roles' },
      { t: '2:30',    cat: 'job',      task: 'Interview prep for any scheduled calls' },
      { t: '3:15',    cat: 'admin',    task: 'Admin: Final consumer claims sweep (anything remaining)' },
      { t: '4:00',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '5:00',    cat: 'fitness',  task: '🧘 ClassPass: Evening yoga' },
      { t: '6:15',    cat: 'personal', task: 'Dinner' },
      { t: '7:15',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Wed, Mar 4', week: 2, tag: 'Deep Job Search',
    theme: 'Research, outreach, applications. Keep HELOC/legal on track.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Heavy pull — rows, pull-ups, face pulls, curls (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'job',      task: 'Deep work: Research 5 new target companies. Map hiring landscape' },
      { t: '11:30',   cat: 'job',      task: 'Apply to 5 roles' },
      { t: '12:30',   cat: 'personal', task: 'Lunch' },
      { t: '1:15',    cat: 'job',      task: 'Cold outreach: 5 more contacts at target companies' },
      { t: '2:00',    cat: 'heloc',    task: 'HELOC: Status check. Employment verification window closing' },
      { t: '2:45',    cat: 'legal',    task: 'BoA: Push attorney engagement. File CFPB rebuttal if ready' },
      { t: '3:30',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '4:15',    cat: 'personal', task: 'Free time' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Thu, Mar 5', week: 2, tag: 'Networking + Pilates',
    theme: 'Network hard. Interview prep. Evening Pilates. TRT: hCG + Anastrozole today.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '7:45',    cat: 'health',   task: '💉 TRT: hCG injection + Anastrozole 1 mg' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Legs + core — front squats, RDLs, lunges, planks (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'job',      task: 'Network: Reach out to 5-10 contacts. Follow up on all warm leads' },
      { t: '11:30',   cat: 'job',      task: 'Apply to 3-5 roles' },
      { t: '12:30',   cat: 'personal', task: 'Lunch' },
      { t: '1:15',    cat: 'job',      task: 'Interview prep: Practice stories, update STAR examples, refine pitch' },
      { t: '2:30',    cat: 'job',      task: 'LinkedIn: Engage with 10+ posts. Stay visible' },
      { t: '3:15',    cat: 'health',   task: 'Confirm all remaining medical appointments before March 19' },
      { t: '3:45',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '5:00',    cat: 'fitness',  task: '🧘 ClassPass: Evening Pilates (Align, SculptHouse, Class Studios)' },
      { t: '6:15',    cat: 'personal', task: 'Dinner' },
      { t: '7:15',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Fri, Mar 6', week: 2, tag: 'Week Wrap-Up',
    theme: 'Close loops. Full pipeline review. Plan final March 19 sprint.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Full body (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'job',      task: 'Pipeline review: Total apps, interviews, pipeline, strategy adjustment' },
      { t: '11:00',   cat: 'heloc',    task: 'HELOC: Final status — what\'s closing? What\'s dead?' },
      { t: '11:45',   cat: 'legal',    task: 'BoA: Attorney engagement status. CFPB rebuttal filed?' },
      { t: '12:30',   cat: 'personal', task: 'Lunch' },
      { t: '1:15',    cat: 'health',   task: 'Final benefits check: Anything left to use before March 19?' },
      { t: '2:00',    cat: 'admin',    task: 'Download any remaining JPMC docs. LinkedIn recommendations requested?' },
      { t: '2:45',    cat: 'job',      task: 'Plan final 13 days of job search strategy' },
      { t: '3:30',    cat: 'fitness',  task: 'Outdoor walk (30-45 min)' },
      { t: '4:30',    cat: 'personal', task: 'Free time' },
      { t: '5:30',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Reward night — out, date, social' },
      { t: '10:30',   cat: 'sleep',    task: 'Wind down (Fri flex)' },
      { t: '11:30',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Sat, Mar 7', week: 2, tag: 'Recovery Day',
    theme: 'Massage + IR sauna. House + prep. Social.',
    blocks: [
      { t: '8:00 AM', cat: 'sleep',    task: 'Wake up naturally (by 8:00)' },
      { t: '8:15',    cat: 'wellness', task: 'Meditation + gratitude journal' },
      { t: '8:30',    cat: 'recovery', task: 'Extended stretch (20-30 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast + coffee' },
      { t: '10:00',   cat: 'recovery', task: '💆 Massage (60-90 min)' },
      { t: '11:30',   cat: 'fitness',  task: 'Outdoor: cycling, hike, or long walk (60-90 min)' },
      { t: '1:00 PM', cat: 'personal', task: 'Lunch' },
      { t: '1:45',    cat: 'personal', task: 'House: clean, laundry, organize' },
      { t: '3:15',    cat: 'personal', task: 'Grocery + meal prep' },
      { t: '5:00',    cat: 'recovery', task: '🧖 IR sauna (30-45 min)' },
      { t: '6:00',    cat: 'personal', task: 'Free time' },
      { t: '7:30',    cat: 'personal', task: 'Social: dinner, friends, date' },
      { t: '10:30',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Sun, Mar 8', week: 2, tag: 'Planning + Reset',
    theme: '11 days to March 19. Lock in the plan. TRT: hCG today.',
    blocks: [
      { t: '8:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '8:15',    cat: 'wellness', task: 'Meditation + gratitude journal' },
      { t: '8:30',    cat: 'recovery', task: 'Extended stretch (20-30 min)' },
      { t: '9:00',    cat: 'health',   task: '💉 TRT: hCG injection' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'personal', task: 'Sprint planning: March 9-19 priorities + unemployment filing prep' },
      { t: '11:00',   cat: 'job',      task: 'Pipeline review — interviews? Offers? What needs acceleration?' },
      { t: '12:00',   cat: 'personal', task: 'Lunch' },
      { t: '12:45',   cat: 'heloc',    task: 'HELOC: Closing timeline confirmed?' },
      { t: '1:30',    cat: 'legal',    task: 'BoA: Final strategy check with attorney' },
      { t: '2:30',    cat: 'recovery', task: '💆 Optional 2nd massage (or rest)' },
      { t: '4:00',    cat: 'fitness',  task: 'Gym: Upper body (60 min)' },
      { t: '5:15',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Free time — recharge for the final sprint' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  // ═══════════════════════════════════════════
  // WEEK 3 — DEADLINE COUNTDOWN (Mar 9–15)
  // ═══════════════════════════════════════════
  {
    date: 'Mon, Mar 9', week: 3, tag: 'IRS Call + Celestica Interview',
    theme: '10 days to March 19. IRS call at 7 AM. TRT injection. Celestica interview at 1:30 PM.',
    blocks: [
      { t: '6:45 AM', cat: 'sleep',    task: 'Wake up early — sunlight, hydrate (IRS call at 7:00)' },
      { t: '7:00',    cat: 'tax',      task: '📞 IRS Call: 1-800-829-1040 (45 min) — 2024 taxes owed. Ask about payment plans, installment agreement. Write down: reference #, rep name, payment timeline, next steps.' },
      { t: '7:45',    cat: 'personal', task: 'Breakfast' },
      { t: '8:00',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '8:15',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:30',    cat: 'health',   task: '💉 TRT: Testosterone injection (Week 2)' },
      { t: '8:45',    cat: 'fitness',  task: 'Gym: Heavy legs — squats, deadlifts, hip thrusts (60 min)' },
      { t: '9:50',    cat: 'health',   task: '🏥 Submit physical paperwork to doctor' },
      { t: '10:15',   cat: 'job',      task: 'Deep work: Apply to 5+ roles' },
      { t: '12:00',   cat: 'job',      task: 'Recruiter follow-ups + cold outreach' },
      { t: '12:45',   cat: 'personal', task: 'Lunch' },
      { t: '1:30',    cat: 'job',      task: '📞 Interview: Celestica' },
      { t: '2:30',    cat: 'admin',    task: '⚠️ INSURANCE RENEWAL (RENEWS MAR 9): Shop auto + home insurance — get 3 quotes. Compare Lemonade, GEICO, Progressive, Allstate. Note: renewal is TODAY so decide quickly.' },
      { t: '3:15',    cat: 'heloc',    task: 'HELOC: Status update — any decisions?' },
      { t: '3:45',    cat: 'health',   task: 'Benefits check: MRA/FSA spending, medical appts status' },
      { t: '4:15',    cat: 'fitness',  task: 'Outdoor walk (30-45 min)' },
      { t: '5:00',    cat: 'personal', task: 'Free time' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'tax',      task: '🧾 Tax: Archive IRS call — reference #, rep name, payment timeline, any docs requested. File notes.' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Tue, Mar 10', week: 3, tag: 'Job Search + Tax Docs',
    theme: 'Applications + benefits push. Compile 2024 income docs for IRS. ClassPass yoga evening.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Heavy push — bench, OHP, incline DB (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'job',      task: 'Apply to 3-5 roles' },
      { t: '11:30',   cat: 'tax',      task: '🧾 Tax: Compile 2024 income docs (30-45 min) — gather W-2s, 1099s, income statements. Create digital folder: Income / Deductions / Business. Have ready in case IRS requests.' },
      { t: '12:30',   cat: 'personal', task: 'Lunch' },
      { t: '1:15',    cat: 'health',   task: 'Final medical appointments — schedule or confirm' },
      { t: '2:00',    cat: 'admin',    task: 'JPMC docs: download anything remaining' },
      { t: '3:00',    cat: 'job',      task: 'Networking outreach — 5 contacts' },
      { t: '4:00',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '5:00',    cat: 'fitness',  task: '🧘 ClassPass: Evening yoga' },
      { t: '6:15',    cat: 'personal', task: 'Dinner' },
      { t: '7:15',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Wed, Mar 11', week: 3, tag: 'Outreach + Tax Docs',
    theme: 'Job outreach, admin cleanup, HELOC/legal check-in. Compile 2024 deduction docs.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Heavy pull — rows, pull-ups, face pulls, curls (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'job',      task: 'Apply to 5 roles' },
      { t: '11:30',   cat: 'tax',      task: '🧾 Tax: Compile 2024 deduction docs (30-45 min) — receipts, invoices, charitable donations, mortgage interest. Scan/organize by category. IRS will ask for specifics if needed.' },
      { t: '12:30',   cat: 'personal', task: 'Lunch' },
      { t: '1:15',    cat: 'heloc',    task: 'HELOC: Push for final decisions' },
      { t: '2:00',    cat: 'legal',    task: 'BoA: Attorney engagement — next steps' },
      { t: '2:45',    cat: 'job',      task: 'Cold outreach: 5 hiring managers at target companies' },
      { t: '3:30',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '4:15',    cat: 'admin',    task: 'Admin cleanup: close any remaining loops' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Thu, Mar 12', week: 3, tag: 'File 2022 Refund + Pilates',
    theme: 'File 2022 tax refund/amended return in the morning. Network, interview prep, Pilates. TRT: hCG + Anastrozole.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '7:45',    cat: 'health',   task: '💉 TRT: hCG injection + Anastrozole 1 mg' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Legs + core — front squats, RDLs, lunges, planks (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '9:45',    cat: 'tax',      task: '🧾 Tax: File 2022 refund claim or Form 1040-X amended return (1-2 hrs). Submit via IRS e-file (preferred) or mail. Document: submission date, confirmation #, timeline (8-12 weeks to process). Keep copy for records.' },
      { t: '11:30',   cat: 'job',      task: 'Network: Follow up on warm leads, reach out to 5-10 contacts' },
      { t: '12:30',   cat: 'personal', task: 'Lunch' },
      { t: '1:15',    cat: 'job',      task: 'Apply to 3-5 roles' },
      { t: '2:30',    cat: 'job',      task: 'Interview prep — STAR examples, pitch refinement' },
      { t: '3:45',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '5:00',    cat: 'fitness',  task: '🧘 ClassPass: Evening Pilates' },
      { t: '6:15',    cat: 'personal', task: 'Dinner' },
      { t: '7:15',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Fri, Mar 13', week: 3, tag: 'Pipeline Review + McKesson Interview',
    theme: 'Close loops. McKesson interview at 3:30 PM. 6 days to March 19.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Full body (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'job',      task: 'Pipeline review: apps, interviews, offers, strategy adjustment' },
      { t: '11:00',   cat: 'health',   task: 'Benefits: Final check — anything left to use?' },
      { t: '11:45',   cat: 'heloc',    task: 'HELOC: Final status' },
      { t: '12:30',   cat: 'personal', task: 'Lunch' },
      { t: '1:15',    cat: 'legal',    task: 'BoA: Attorney status check' },
      { t: '2:00',    cat: 'job',      task: 'Apply to 3 roles' },
      { t: '2:45',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '3:30',    cat: 'job',      task: '📞 Interview: McKesson' },
      { t: '4:30',    cat: 'personal', task: 'Post-interview notes — capture key takeaways, follow-up items' },
      { t: '5:30',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Reward night — out, socialize' },
      { t: '10:30',   cat: 'sleep',    task: 'Wind down (Fri flex)' },
      { t: '11:30',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Sat, Mar 14', week: 3, tag: 'Recovery Day',
    theme: 'Massage + IR sauna. House + meal prep. Social.',
    blocks: [
      { t: '8:00 AM', cat: 'sleep',    task: 'Wake up naturally (by 8:00)' },
      { t: '8:15',    cat: 'wellness', task: 'Meditation + gratitude journal' },
      { t: '8:30',    cat: 'recovery', task: 'Extended stretch (20-30 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast + coffee' },
      { t: '10:00',   cat: 'recovery', task: '💆 Massage (60-90 min)' },
      { t: '11:30',   cat: 'fitness',  task: 'Outdoor: cycling, hike, or long walk (60-90 min)' },
      { t: '1:00 PM', cat: 'personal', task: 'Lunch' },
      { t: '1:45',    cat: 'personal', task: 'House: clean, laundry, organize' },
      { t: '3:15',    cat: 'personal', task: 'Grocery + meal prep' },
      { t: '5:00',    cat: 'recovery', task: '🧖 IR sauna (30-45 min)' },
      { t: '6:00',    cat: 'personal', task: 'Free time' },
      { t: '7:30',    cat: 'personal', task: 'Social: dinner, friends, date' },
      { t: '10:30',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Sun, Mar 15', week: 3, tag: 'Deadline Week Prep',
    theme: '4 days to March 19. Final prep. TRT: hCG today.',
    blocks: [
      { t: '8:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '8:15',    cat: 'wellness', task: 'Meditation + gratitude journal' },
      { t: '8:30',    cat: 'recovery', task: 'Extended stretch (20-30 min)' },
      { t: '9:00',    cat: 'health',   task: '💉 TRT: hCG injection' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'personal', task: 'Deadline week planning: Map Mon-Thu tasks for March 19 closeout' },
      { t: '11:00',   cat: 'job',      task: 'Pipeline review — interviews? Offers? Follow-ups needed?' },
      { t: '12:00',   cat: 'personal', task: 'Lunch' },
      { t: '12:45',   cat: 'admin',    task: 'Pre-deadline checklist: JPMC docs, portal access, unemployment prep' },
      { t: '2:00',    cat: 'recovery', task: '💆 Optional 2nd massage (or rest)' },
      { t: '4:00',    cat: 'fitness',  task: 'Gym: Upper body (60 min)' },
      { t: '5:15',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Free time — recharge for deadline week' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  // ═══════════════════════════════════════════
  // WEEK 4 — DEADLINE WEEK (Mar 16–22)
  // ═══════════════════════════════════════════
  {
    date: 'Mon, Mar 16', week: 4, tag: '3 Days to Deadline',
    theme: 'March 19 in 3 days. Final JPMC tasks. TRT: Testosterone injection (Week 3).',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '7:45',    cat: 'health',   task: '💉 TRT: Testosterone injection (Week 3)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Heavy legs — squats, deadlifts, hip thrusts (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '9:45',    cat: 'tax',      task: '🧾 Tax: Check email for any IRS responses (5 min). Flag immediately if present. Property tax: email hired professional for status update (5 min).' },
      { t: '10:00',   cat: 'admin',    task: 'JPMC final push: Download all remaining docs, certs, pay stubs' },
      { t: '11:00',   cat: 'health',   task: 'Final Rx refills — 90-day supplies while insurance active' },
      { t: '12:00',   cat: 'personal', task: 'Lunch' },
      { t: '12:45',   cat: 'job',      task: 'Apply to 3-5 roles' },
      { t: '2:00',    cat: 'job',      task: 'Interview follow-ups' },
      { t: '3:00',    cat: 'heloc',    task: 'HELOC: Confirm status — employment verification before Mar 19' },
      { t: '4:00',    cat: 'fitness',  task: 'Outdoor walk (30-45 min)' },
      { t: '5:00',    cat: 'personal', task: 'Free time' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Tue, Mar 17', week: 4, tag: '2 Days to Deadline',
    theme: 'Final benefits sweep. Last medical appts. ClassPass yoga.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Heavy push — bench, OHP, incline DB (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'health',   task: 'Final MRA/FSA spending — use every dollar' },
      { t: '10:45',   cat: 'health',   task: 'COBRA vs marketplace — final decision' },
      { t: '11:30',   cat: 'admin',    task: 'JPMC: Complete any remaining learning/certifications' },
      { t: '12:15',   cat: 'personal', task: 'Lunch' },
      { t: '1:00 PM', cat: 'job',      task: 'Apply to 3 roles' },
      { t: '2:00',    cat: 'admin',    task: 'Request LinkedIn recommendations (3-5 colleagues)' },
      { t: '3:00',    cat: 'admin',    task: 'Unemployment filing prep: gather all required info' },
      { t: '4:00',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '5:00',    cat: 'fitness',  task: '🧘 ClassPass: Evening yoga' },
      { t: '6:15',    cat: 'personal', task: 'Dinner' },
      { t: '7:15',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Wed, Mar 18', week: 4, tag: '1 Day to Deadline',
    theme: 'Last day before JPMC ends. Final downloads, access, prep.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Heavy pull — rows, pull-ups, face pulls, curls (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'admin',    task: '⚠️ FINAL: Download ALL JPMC portal data — pay stubs, W-2s, reviews, 401(k)' },
      { t: '11:00',   cat: 'admin',    task: 'Verify Hyatt Legal Plan consultation completed' },
      { t: '11:30',   cat: 'admin',    task: 'Call Empower — confirm 401(k) forfeiture documented in writing' },
      { t: '12:15',   cat: 'personal', task: 'Lunch' },
      { t: '1:00 PM', cat: 'admin',    task: 'Severance team: final follow-up on bonus discrepancy ($5K)' },
      { t: '1:45',    cat: 'health',   task: 'Confirm COBRA enrollment or marketplace selection' },
      { t: '2:30',    cat: 'job',      task: 'Job search: 3 applications' },
      { t: '3:30',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '4:15',    cat: 'personal', task: 'Free time' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Free time — rest up for tomorrow' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Thu, Mar 19', week: 4, tag: '🔴 JPMC LAST DAY',
    theme: 'MARCH 19 — JPMC last day. Close everything out. File unemployment. TRT: hCG + Anastrozole.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '7:45',    cat: 'health',   task: '💉 TRT: hCG injection + Anastrozole 1 mg' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Legs + core (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'admin',    task: '🔴 JPMC: Final portal access — last chance to download anything' },
      { t: '11:00',   cat: 'admin',    task: 'File for unemployment (or schedule for Mar 20)' },
      { t: '12:00',   cat: 'personal', task: 'Lunch' },
      { t: '12:45',   cat: 'health',   task: 'Verify all benefits used: MRA, FSA, legal plan, Rx refills' },
      { t: '1:30',    cat: 'admin',    task: 'Final JPMC closeout: badge, equipment, access confirmation' },
      { t: '2:30',    cat: 'job',      task: 'Job search continues — apply to 3 roles' },
      { t: '3:30',    cat: 'fitness',  task: 'Outdoor walk (30-45 min) — breathe, new chapter starts' },
      { t: '4:30',    cat: 'personal', task: 'Free time' },
      { t: '6:00',    cat: 'personal', task: 'Dinner — celebrate closing this chapter' },
      { t: '7:00',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Fri, Mar 20', week: 4, tag: 'Day 1 Post-JPMC',
    theme: 'New chapter begins. File unemployment if not done. Decompress.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling — reflect on the transition' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Full body (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'admin',    task: 'File unemployment (if not done yesterday)' },
      { t: '11:00',   cat: 'job',      task: 'Job search: Apply to 5 roles — full focus now' },
      { t: '12:30',   cat: 'personal', task: 'Lunch' },
      { t: '1:15',    cat: 'job',      task: 'Recruiter follow-ups + interview scheduling' },
      { t: '2:30',    cat: 'job',      task: 'LinkedIn: Post about transition + engage' },
      { t: '3:30',    cat: 'fitness',  task: 'Outdoor walk (30-45 min)' },
      { t: '4:30',    cat: 'personal', task: 'Free time' },
      { t: '5:30',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Reward night — celebrate the new chapter' },
      { t: '10:30',   cat: 'sleep',    task: 'Wind down (Fri flex)' },
      { t: '11:30',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Sat, Mar 21', week: 4, tag: 'Recovery Day',
    theme: 'Massage + sauna. Recharge after a big week.',
    blocks: [
      { t: '8:00 AM', cat: 'sleep',    task: 'Wake up naturally (by 8:00)' },
      { t: '8:15',    cat: 'wellness', task: 'Meditation + gratitude journal' },
      { t: '8:30',    cat: 'recovery', task: 'Extended stretch (20-30 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast + coffee' },
      { t: '10:00',   cat: 'recovery', task: '💆 Massage (60-90 min)' },
      { t: '11:30',   cat: 'fitness',  task: 'Outdoor: cycling, hike, or long walk (60-90 min)' },
      { t: '1:00 PM', cat: 'personal', task: 'Lunch' },
      { t: '1:45',    cat: 'personal', task: 'House: clean, laundry, organize' },
      { t: '3:15',    cat: 'personal', task: 'Grocery + meal prep' },
      { t: '5:00',    cat: 'recovery', task: '🧖 IR sauna (30-45 min)' },
      { t: '6:00',    cat: 'personal', task: 'Free time' },
      { t: '7:30',    cat: 'personal', task: 'Social: dinner, friends, date' },
      { t: '10:30',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Sun, Mar 22', week: 4, tag: 'New Chapter Planning',
    theme: 'Plan the post-JPMC phase. Full job search mode. TRT: hCG today.',
    blocks: [
      { t: '8:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '8:15',    cat: 'wellness', task: 'Meditation + gratitude journal' },
      { t: '8:30',    cat: 'recovery', task: 'Extended stretch (20-30 min)' },
      { t: '9:00',    cat: 'health',   task: '💉 TRT: hCG injection' },
      { t: '9:10',    cat: 'tax',      task: '🧾 Tax weekly check-in (10 min): Email property tax professional for status. Check IRS responses. Monitor 2022 refund at IRS "Where\'s My Refund".' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'personal', task: 'Post-JPMC sprint planning: Mar 23-31 priorities, new daily structure, budget review' },
      { t: '11:00',   cat: 'job',      task: 'Pipeline review — what\'s hot, what needs follow-up?' },
      { t: '12:00',   cat: 'personal', task: 'Lunch' },
      { t: '12:45',   cat: 'legal',    task: 'BoA: Attorney engagement — next steps post-employment' },
      { t: '1:30',    cat: 'heloc',    task: 'HELOC: Final status — what closed, what\'s pending?' },
      { t: '2:30',    cat: 'recovery', task: '💆 Optional 2nd massage (or rest)' },
      { t: '4:00',    cat: 'fitness',  task: 'Gym: Upper body (60 min)' },
      { t: '5:15',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  // ═══════════════════════════════════════════
  // WEEK 5 — NEW CHAPTER (Mar 23–31)
  // ═══════════════════════════════════════════
  {
    date: 'Mon, Mar 23', week: 5, tag: 'Full Job Search Mode',
    theme: 'All-in on job search. No more JPMC distractions. TRT: Testosterone injection (Week 4).',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '7:45',    cat: 'health',   task: '💉 TRT: Testosterone injection (Week 4)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Heavy legs — squats, deadlifts, hip thrusts (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'job',      task: 'Deep work: Apply to 5+ roles' },
      { t: '12:00',   cat: 'job',      task: 'Recruiter calls + cold outreach' },
      { t: '12:45',   cat: 'personal', task: 'Lunch' },
      { t: '1:30',    cat: 'job',      task: 'LinkedIn: Thought leadership + networking' },
      { t: '2:30',    cat: 'job',      task: 'Interview prep / follow-ups' },
      { t: '4:00',    cat: 'fitness',  task: 'Outdoor walk (30-45 min)' },
      { t: '5:00',    cat: 'personal', task: 'Free time' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Tue, Mar 24', week: 5, tag: 'Job Search + Yoga',
    theme: 'Applications, interviews, ClassPass yoga evening.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Heavy push — bench, OHP, incline DB (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'job',      task: 'Apply to 3-5 roles' },
      { t: '11:30',   cat: 'job',      task: 'Interview prep + follow-ups' },
      { t: '12:30',   cat: 'personal', task: 'Lunch' },
      { t: '1:15',    cat: 'job',      task: 'Networking: 5 outreach messages' },
      { t: '2:30',    cat: 'personal', task: 'Open block — personal projects or errands' },
      { t: '4:00',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '5:00',    cat: 'fitness',  task: '🧘 ClassPass: Evening yoga' },
      { t: '6:15',    cat: 'personal', task: 'Dinner' },
      { t: '7:15',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Wed, Mar 25', week: 5, tag: 'Deep Work',
    theme: 'Research, outreach, applications.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Heavy pull — rows, pull-ups, face pulls, curls (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'job',      task: 'Deep work: Research target companies + apply to 5 roles' },
      { t: '12:00',   cat: 'job',      task: 'Cold outreach: 5 hiring managers' },
      { t: '12:30',   cat: 'personal', task: 'Lunch' },
      { t: '1:15',    cat: 'personal', task: 'Open block — personal projects or errands' },
      { t: '2:30',    cat: 'legal',    task: 'BoA: Attorney / case status check' },
      { t: '3:30',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '4:15',    cat: 'personal', task: 'Free time' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Thu, Mar 26', week: 5, tag: 'Networking + Pilates',
    theme: 'Network, interview prep, Pilates. TRT: hCG + Anastrozole today.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '7:45',    cat: 'health',   task: '💉 TRT: hCG injection + Anastrozole 1 mg' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Legs + core — front squats, RDLs, lunges, planks (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'job',      task: 'Network: Follow up on all warm leads' },
      { t: '11:30',   cat: 'job',      task: 'Apply to 3-5 roles' },
      { t: '12:30',   cat: 'personal', task: 'Lunch' },
      { t: '1:15',    cat: 'job',      task: 'Interview prep — STAR examples, pitch' },
      { t: '2:30',    cat: 'personal', task: 'Open block — personal projects or errands' },
      { t: '3:45',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '5:00',    cat: 'fitness',  task: '🧘 ClassPass: Evening Pilates' },
      { t: '6:15',    cat: 'personal', task: 'Dinner' },
      { t: '7:15',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Fri, Mar 27', week: 5, tag: 'Pipeline Review',
    theme: 'Weekly review. Close loops. Reward night.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Full body (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'job',      task: 'Pipeline review: apps, interviews, offers, strategy' },
      { t: '11:00',   cat: 'job',      task: 'Apply to 3 roles' },
      { t: '12:00',   cat: 'personal', task: 'Lunch' },
      { t: '12:45',   cat: 'personal', task: 'Open block — personal projects or errands' },
      { t: '2:00',    cat: 'job',      task: 'Follow-ups + interview scheduling' },
      { t: '3:00',    cat: 'fitness',  task: 'Outdoor walk (30-45 min)' },
      { t: '4:00',    cat: 'personal', task: 'Free time' },
      { t: '5:30',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Reward night — out, socialize' },
      { t: '10:30',   cat: 'sleep',    task: 'Wind down (Fri flex)' },
      { t: '11:30',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Sat, Mar 28', week: 5, tag: 'Recovery Day',
    theme: 'Massage + sauna. House + meal prep. Social.',
    blocks: [
      { t: '8:00 AM', cat: 'sleep',    task: 'Wake up naturally (by 8:00)' },
      { t: '8:15',    cat: 'wellness', task: 'Meditation + gratitude journal' },
      { t: '8:30',    cat: 'recovery', task: 'Extended stretch (20-30 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast + coffee' },
      { t: '10:00',   cat: 'recovery', task: '💆 Massage (60-90 min)' },
      { t: '11:30',   cat: 'fitness',  task: 'Outdoor: cycling, hike, or long walk (60-90 min)' },
      { t: '1:00 PM', cat: 'personal', task: 'Lunch' },
      { t: '1:45',    cat: 'personal', task: 'House: clean, laundry, organize' },
      { t: '3:15',    cat: 'personal', task: 'Grocery + meal prep' },
      { t: '5:00',    cat: 'recovery', task: '🧖 IR sauna (30-45 min)' },
      { t: '6:00',    cat: 'personal', task: 'Free time' },
      { t: '7:30',    cat: 'personal', task: 'Social: dinner, friends, date' },
      { t: '10:30',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Sun, Mar 29', week: 5, tag: 'Monthly Review',
    theme: 'End of March in sight. Review the whole month. TRT: hCG today.',
    blocks: [
      { t: '8:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '8:15',    cat: 'wellness', task: 'Meditation + gratitude journal' },
      { t: '8:30',    cat: 'recovery', task: 'Extended stretch (20-30 min)' },
      { t: '9:00',    cat: 'health',   task: '💉 TRT: hCG injection' },
      { t: '9:10',    cat: 'tax',      task: '🧾 Tax weekly check-in (10 min): Check IRS responses, monitor 2022 refund ("Where\'s My Refund"), property tax professional status. File weekly unemployment claim (Texas Workforce Commission, ~10 min).' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'personal', task: 'Monthly review: What worked, what didn\'t, April planning' },
      { t: '11:00',   cat: 'job',      task: 'Pipeline review — where do things stand?' },
      { t: '12:00',   cat: 'personal', task: 'Lunch' },
      { t: '12:45',   cat: 'personal', task: 'Open block — personal projects' },
      { t: '2:00',    cat: 'recovery', task: '💆 Optional 2nd massage (or rest)' },
      { t: '4:00',    cat: 'fitness',  task: 'Gym: Upper body (60 min)' },
      { t: '5:15',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Mon, Mar 30', week: 5, tag: 'April Prep',
    theme: 'Last weekday push of March. Job search + new month prep.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Heavy legs — squats, deadlifts, hip thrusts (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'job',      task: 'Apply to 5+ roles' },
      { t: '12:00',   cat: 'job',      task: 'Recruiter calls + follow-ups' },
      { t: '12:45',   cat: 'personal', task: 'Lunch' },
      { t: '1:30',    cat: 'job',      task: 'LinkedIn engagement + networking' },
      { t: '2:30',    cat: 'personal', task: 'Open block — April goals, budget, planning' },
      { t: '4:00',    cat: 'fitness',  task: 'Outdoor walk (30-45 min)' },
      { t: '5:00',    cat: 'personal', task: 'Free time' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
  {
    date: 'Tue, Mar 31', week: 5, tag: 'End of March',
    theme: 'Last day of March. Close out the month strong.',
    blocks: [
      { t: '7:00 AM', cat: 'sleep',    task: 'Wake up — sunlight, hydrate' },
      { t: '7:15',    cat: 'wellness', task: 'Meditation + journaling' },
      { t: '7:30',    cat: 'recovery', task: 'Morning stretch (15-20 min)' },
      { t: '8:00',    cat: 'fitness',  task: 'Gym: Heavy push — bench, OHP, incline DB (60 min)' },
      { t: '9:15',    cat: 'personal', task: 'Breakfast' },
      { t: '10:00',   cat: 'job',      task: 'Apply to 3-5 roles' },
      { t: '11:30',   cat: 'job',      task: 'Interview prep + follow-ups' },
      { t: '12:30',   cat: 'personal', task: 'Lunch' },
      { t: '1:15',    cat: 'personal', task: 'Open block — personal projects or errands' },
      { t: '2:30',    cat: 'personal', task: 'End-of-month wrap: review March, set April priorities' },
      { t: '3:30',    cat: 'fitness',  task: 'Outdoor walk (30 min)' },
      { t: '4:15',    cat: 'personal', task: 'Free time' },
      { t: '6:00',    cat: 'personal', task: 'Dinner' },
      { t: '7:00',    cat: 'personal', task: 'Free time' },
      { t: '10:00',   cat: 'sleep',    task: 'Wind down' },
      { t: '11:00',   cat: 'sleep',    task: 'Lights out' },
    ],
  },
]

// ── Reference data ────────────────────────────────────────

export const SLEEP_RULES: SleepRule[] = [
  { icon: '⏰', rule: 'Wake at 7:00 AM weekdays, 8:00 AM weekends — no snooze' },
  { icon: '☀️', rule: 'Sunlight within 10 min of waking — open blinds or step outside' },
  { icon: '☕', rule: 'No caffeine after 1:00 PM' },
  { icon: '📵', rule: 'No screens after 10:00 PM — phone on Do Not Disturb' },
  { icon: '💡', rule: 'Dim all lights at 10 PM — warm/amber only' },
  { icon: '❄️', rule: 'Bedroom: 65-68°F, blackout dark, quiet' },
  { icon: '📖', rule: 'Wind-down: skincare → read or journal → lights out 11:00 PM' },
  { icon: '🎯', rule: 'Target: 8 hours every night (11 PM → 7 AM)' },
]

export const WEEKLY_TEMPLATE: WeeklyRow[] = [
  { d: 'Mon', am: 'Stretch → Heavy legs/push (gym)', pm: 'Outdoor walk + deep work' },
  { d: 'Tue', am: 'Stretch → Heavy pull/push (gym)', pm: 'Walk → ClassPass yoga/Pilates 5-6 PM' },
  { d: 'Wed', am: 'Stretch → Heavy pull/legs (gym)', pm: 'Outdoor walk + free time' },
  { d: 'Thu', am: 'Stretch → Legs + core (gym)',     pm: 'Walk → ClassPass yoga/Pilates 5-6 PM' },
  { d: 'Fri', am: 'Stretch → Full body (gym)',       pm: 'Outdoor walk + reward night' },
  { d: 'Sat', am: 'Extended stretch → 💆 Massage',  pm: 'Outdoor cardio → 🧖 IR sauna' },
  { d: 'Sun', am: 'Extended stretch → Planning',     pm: 'Gym upper → optional 💆 2nd massage' },
]

export const RECOVERY_STACK: RecoveryItem[] = [
  { icon: '🧘', title: 'Daily Stretch (every morning)',        desc: '15-20 min weekdays, 20-30 min weekends. Hips, hamstrings, thoracic spine, shoulders' },
  { icon: '💆', title: 'Massage (1-2x/week — Sat + optional Sun)', desc: '60-90 min. Sports or deep tissue. Book through ClassPass or local therapist' },
  { icon: '🧖', title: 'IR Sauna (1x/week — Saturday PM)',    desc: '30-45 min after outdoor cardio. Pair with cold plunge if available' },
  { icon: '🚶', title: 'Daily Walk (30-45 min — every afternoon)', desc: 'Between deep work blocks. Cardio + mental reset + vitamin D' },
]

export const CLASSPASS: ClassPassItem[] = [
  { type: 'Yoga (Tue/Thu 5-6 PM)',          studios: 'Black Swan Yoga (heated), Ritual One, O2 Studio, Soul Friends' },
  { type: 'Pilates/Lagree (Tue/Thu 5-6 PM)', studios: 'Align Studio (infrared), SculptHouse, [solidcore], Class Studios' },
  { type: 'Recovery/Sauna',                  studios: 'TruFusion, local recovery clinics with IR sauna + cryo' },
]

export const MAR19: ChecklistItem[] = [
  { c: 'health', t: 'Physical + blood work (Fri Feb 20 @ 10 AM)' },
  { c: 'health', t: 'Schedule dentist' },
  { c: 'health', t: 'Schedule dermatology' },
  { c: 'health', t: 'Refill prescriptions — 90-day supplies' },
  { c: 'health', t: 'Submit physical paperwork to doctor' },
  { c: 'health', t: 'MRA balance — spend on eligible health items' },
  { c: 'health', t: 'FSA balance — stock up on OTC' },
  { c: 'health', t: 'COBRA details + marketplace quotes' },
  { c: 'admin',  t: 'Download JPMC docs: pay stubs, W-2s, reviews, 401(k)' },
  { c: 'admin',  t: 'Book Hyatt Legal Plan consultation(s)' },
  { c: 'admin',  t: 'Call Empower — 401(k) forfeiture in writing' },
  { c: 'admin',  t: 'Severance team: bonus discrepancy ($5K)' },
  { c: 'admin',  t: 'Request 3-5 LinkedIn recommendations' },
  { c: 'admin',  t: 'File unemployment March 19 or 20' },
]

export const RULES: string[] = [
  'Max 2 deep-work blocks/day (60-90 min each)',
  'Max 1 admin block/day (30-45 min)',
  'One major theme per day — check the tag',
  'Job search every weekday, no exceptions',
  'Stop when the block ends — no overrun',
  'No catch-up mentality — execute today\'s plan',
  'Morning stretch daily — non-negotiable',
  'Heavy lift 5x/week (Mon-Fri mornings)',
  'ClassPass 2x/week (Tue + Thu 5-6 PM)',
  'Outdoor walk daily — minimum 30 min (afternoon)',
  'Massage 1-2x/week (weekends)',
  'IR sauna 1x/week (Saturday PM)',
]

export const SUCCESS: string[] = [
  'Multiple HELOCs active with a clear front-runner',
  'Attorney pipeline opened and responses in hand',
  'All health appointments scheduled or completed',
  'Benefits fully leveraged before March 19',
  '40+ job applications, 5+ recruiter conversations',
  'Sleep locked: 8 hrs/night (11 PM → 7 AM)',
  'Lifting 5x/week + 2 ClassPass classes established',
  'Daily stretch + weekly massage/sauna habit built',
  'No loose admin anxiety loops',
]

// ── Milestones / critical deadlines ────────────────────────

export interface Milestone {
  label: string
  shortLabel: string
  icon: string
  isoDate: string        // YYYY-MM-DD for countdown calculation
  urgency: 'critical' | 'high' | 'medium' | 'low'
  note: string
  week?: number          // schedule week to jump to on click
  dayIdx?: number        // day index within that week
}

export const MILESTONES: Milestone[] = [
  {
    label: 'HELOC Close + JPMC Last Day',
    shortLabel: 'HELOC / JPMC',
    icon: '🔴',
    isoDate: '2026-03-19',
    urgency: 'critical',
    note: 'Must close HELOC while still employed at JPMC',
    week: 4,
    dayIdx: 2,
  },
  {
    label: 'DCAD Protest Deadline',
    shortLabel: 'DCAD Protest',
    icon: '🏠',
    isoDate: '2026-05-15',
    urgency: 'high',
    note: 'File at ifile.dallascad.org — dispute $850K valuation',
  },
  {
    label: 'Best Buy Promo Expires',
    shortLabel: 'Best Buy',
    icon: '💳',
    isoDate: '2026-06-27',
    urgency: 'high',
    note: '$1,312 — $339 deferred interest if missed',
  },
  {
    label: 'Chase 0% Promos Expire',
    shortLabel: 'Chase Promos',
    icon: '💳',
    isoDate: '2026-12-01',
    urgency: 'medium',
    note: '$36,427 — pay from HELOC as buckets expire Jul–Dec',
  },
  {
    label: 'Roth Conversion Deadline',
    shortLabel: 'Roth Window',
    icon: '💰',
    isoDate: '2026-12-31',
    urgency: 'medium',
    note: 'Low-income year — convert up to $23K at 22% bracket',
  },
  {
    label: 'Citi Diamond 0% Expires',
    shortLabel: 'Citi Diamond',
    icon: '💳',
    isoDate: '2027-06-18',
    urgency: 'low',
    note: '$12,476 — longest runway, pay from HELOC by Jun 2027',
  },
]

// ── Derived helpers ────────────────────────────────────────

export const WEEK_LABELS: Record<number, string> = {
  1: 'Feb 27–Mar 2',
  2: 'Mar 3–9',
  3: 'Mar 10–16',
  4: '⚠️ Mar 17–23',
  5: 'Mar 24–31',
}

export function getDaysForWeek(week: number): Day[] {
  return DAYS.filter(d => d.week === week)
}
