-- =============================================================
-- Life Plan Seed Data — Auto-generated from life-plan-data.ts
-- DO NOT EDIT MANUALLY — re-run scripts/generate-life-plan-seed.ts
-- =============================================================

-- Sections
INSERT INTO life_plan_sections (id, name, color_hex, sort_order) VALUES
  ('health', 'Health & Fitness', '#C1121F', 1),
  ('career', 'Business & Career', '#0077B6', 2),
  ('relationships', 'Relationships & Romance', '#E63946', 3),
  ('family', 'Family & Friends', '#F4A261', 4),
  ('finance', 'Finance', '#2D6A4F', 5),
  ('home', 'Home & Lifestyle', '#E76F51', 6),
  ('fun', 'Fun & Recreation', '#7209B7', 7),
  ('memberships', 'Memberships & Access', '#264653', 8),
  ('personal-dev', 'Personal Development', '#2A9D8F', 9),
  ('spiritual', 'Spiritual', '#4361EE', 10);

-- Goals
INSERT INTO life_plan_goals (section_id, timeframe, timeframe_label, category_header, goal_text, sort_order) VALUES
  ('health', '40', '1 YEAR (Age 40)', 'Physique & Weight:', 'Complete 75 Hard (Q1)', 1),
  ('health', '40', '1 YEAR (Age 40)', 'Physique & Weight:', 'Lose 10–15 lbs (210 → 195–190)', 2),
  ('health', '40', '1 YEAR (Age 40)', 'Physique & Weight:', 'Goal weight under 200 lbs (stretch: 190)', 3),
  ('health', '40', '1 YEAR (Age 40)', 'Physique & Weight:', 'Body fat down to 12% (from 14.5%)', 4),
  ('health', '40', '1 YEAR (Age 40)', 'Physique & Weight:', 'Visible abs / lose love handles', 5),
  ('health', '40', '1 YEAR (Age 40)', 'Physique & Weight:', 'Stronger core and obliques', 6),
  ('health', '40', '1 YEAR (Age 40)', 'Physique & Weight:', 'Strengthen legs, glutes, lower back', 7),
  ('health', '40', '1 YEAR (Age 40)', 'Physique & Weight:', 'Thinner jawline / more refined face structure', 8),
  ('health', '40', '1 YEAR (Age 40)', 'Health & Wellness:', 'Heal gut issues (IBS)', 9),
  ('health', '40', '1 YEAR (Age 40)', 'Health & Wellness:', 'Healthier skin / less wrinkles / look younger', 10),
  ('health', '40', '1 YEAR (Age 40)', 'Health & Wellness:', 'Whiter teeth', 11),
  ('health', '40', '1 YEAR (Age 40)', 'Health & Wellness:', 'Limit alcohol substantially or altogether', 12),
  ('health', '40', '1 YEAR (Age 40)', 'Fitness Routine:', 'Get back into yoga — start taking classes', 13),
  ('health', '40', '1 YEAR (Age 40)', 'Fitness Routine:', 'Join a bootcamp class', 14),
  ('health', '40', '1 YEAR (Age 40)', 'Fitness Routine:', 'Find a fit crew / fitness community in Dallas', 15),
  ('health', '40', '1 YEAR (Age 40)', 'Fitness Routine:', 'Focus on recovery — join a recovery clinic (cryo, sauna, cold plunge)', 16),
  ('health', '40', '1 YEAR (Age 40)', 'Flexibility & Mobility:', 'Stretch more / become more flexible', 17),
  ('health', '40', '1 YEAR (Age 40)', 'Flexibility & Mobility:', 'Regular mobility work', 18),
  ('health', '40', '1 YEAR (Age 40)', 'Biohacking & Longevity:', 'Continue TRT treatments', 19),
  ('health', '40', '1 YEAR (Age 40)', 'Biohacking & Longevity:', 'HGH or Sermorelin', 20),
  ('health', '40', '1 YEAR (Age 40)', 'Biohacking & Longevity:', 'hCG / fertility treatments', 21),
  ('health', '40', '1 YEAR (Age 40)', 'Biohacking & Longevity:', 'Peptides (BPC-157, others for longevity/healing)', 22),
  ('health', '40', '1 YEAR (Age 40)', 'Biohacking & Longevity:', 'Regular bloodwork (2x/year)', 23),
  ('health', '45', '5 YEARS (Age 45)', 'Physique:', 'Maintain peak fitness and performance', 24),
  ('health', '45', '5 YEARS (Age 45)', 'Physique:', 'Weight at 190 or below', 25),
  ('health', '45', '5 YEARS (Age 45)', 'Physique:', 'Stay lean at 10–12% body fat', 26),
  ('health', '45', '5 YEARS (Age 45)', 'Physique:', 'Visible abs maintained', 27),
  ('health', '45', '5 YEARS (Age 45)', 'Physique:', 'Alcohol-free except very special occasions', 28),
  ('health', '45', '5 YEARS (Age 45)', 'Ideal Weekly Routine:', 'Gym 5–7 days/week', 29),
  ('health', '45', '5 YEARS (Age 45)', 'Ideal Weekly Routine:', 'Yoga 2–3x/week', 30),
  ('health', '45', '5 YEARS (Age 45)', 'Ideal Weekly Routine:', 'Mix of lifting and bootcamp classes', 31),
  ('health', '45', '5 YEARS (Age 45)', 'Ideal Weekly Routine:', 'Walk outdoors 3–4 days/week', 32),
  ('health', '45', '5 YEARS (Age 45)', 'Ideal Weekly Routine:', 'Cycling on non-walk days', 33),
  ('health', '45', '5 YEARS (Age 45)', 'Sports & Activities:', 'Tennis (solid player)', 34),
  ('health', '45', '5 YEARS (Age 45)', 'Sports & Activities:', 'Golf (playing regularly)', 35),
  ('health', '45', '5 YEARS (Age 45)', 'Sports & Activities:', 'Cycling (regular + big cycling trips)', 36),
  ('health', '45', '5 YEARS (Age 45)', 'Sports & Activities:', 'Hiking trips annually', 37),
  ('health', '45', '5 YEARS (Age 45)', 'Sports & Activities:', 'Skiing annually', 38),
  ('health', '45', '5 YEARS (Age 45)', 'Sports & Activities:', 'Camping / outdoor activities', 39),
  ('health', '45', '5 YEARS (Age 45)', 'Martial Arts & Tactical:', 'Tactical self-defense and shooting', 40),
  ('health', '45', '5 YEARS (Age 45)', 'Martial Arts & Tactical:', 'Krav Maga / MMA', 41),
  ('health', '45', '5 YEARS (Age 45)', 'Martial Arts & Tactical:', 'Tactical training courses', 42),
  ('health', '45', '5 YEARS (Age 45)', 'Biohacking & Longevity:', 'Hormone optimization continued', 43),
  ('health', '45', '5 YEARS (Age 45)', 'Biohacking & Longevity:', 'Peptides for longevity and healing', 44),
  ('health', '45', '5 YEARS (Age 45)', 'Biohacking & Longevity:', 'Stem cell treatments', 45),
  ('health', '45', '5 YEARS (Age 45)', 'Biohacking & Longevity:', 'Annual fitness retreat', 46),
  ('health', '50', '10 YEARS (Age 50)', NULL, 'Still active and in peak shape', 47),
  ('health', '50', '10 YEARS (Age 50)', NULL, 'Visible abs maintained, 10–12% body fat', 48),
  ('health', '50', '10 YEARS (Age 50)', NULL, 'Look like I''m in my 40s or late 30s', 49),
  ('health', '50', '10 YEARS (Age 50)', NULL, 'Tennis, golf, cycling, skiing, hiking regularly', 50),
  ('health', '50', '10 YEARS (Age 50)', NULL, 'Complete a famous hike/climb', 51),
  ('health', '50', '10 YEARS (Age 50)', NULL, 'Complete a famous cycling challenge', 52),
  ('health', '50', '10 YEARS (Age 50)', NULL, 'Advanced longevity treatments (NAD+, glutathione, stem cells)', 53),
  ('health', '50', '10 YEARS (Age 50)', NULL, 'Sauna in house', 54),
  ('health', '50', '10 YEARS (Age 50)', NULL, 'Wake up pain-free, feel 20 years younger', 55),
  ('health', '60', '20 YEARS (Age 60)', NULL, 'Still maintaining abs and low body fat', 56),
  ('health', '60', '20 YEARS (Age 60)', NULL, 'Fit, energized, and active', 57),
  ('health', '60', '20 YEARS (Age 60)', NULL, 'More yoga, walking, regenerative activities', 58),
  ('health', '60', '20 YEARS (Age 60)', NULL, 'Golf, tennis, cycling, skiing, hiking', 59),
  ('health', '60', '20 YEARS (Age 60)', NULL, 'Playing with grandkids', 60),
  ('health', '60', '20 YEARS (Age 60)', NULL, 'Feel like I''m 40 — energized, pain-free, thriving', 61),
  ('career', '40', '1 YEAR (Age 40)', 'Role & Compensation:', 'VP at Fintech, Digital Bank, or Hyperscaler', 62),
  ('career', '40', '1 YEAR (Age 40)', 'Role & Compensation:', 'Total comp: $300–400K+ (base $230–260K)', 63),
  ('career', '40', '1 YEAR (Age 40)', 'Role & Compensation:', 'Negotiate sign-on bonus $50–100K', 64),
  ('career', '40', '1 YEAR (Age 40)', 'Skills & Development:', 'Sharpen executive presence and board-readiness', 65),
  ('career', '40', '1 YEAR (Age 40)', 'Skills & Development:', 'Find C-suite mentor (CIO/CTO/CDO/CAIO)', 66),
  ('career', '40', '1 YEAR (Age 40)', 'Skills & Development:', 'Find political mentor', 67),
  ('career', '40', '1 YEAR (Age 40)', 'Skills & Development:', 'Maximize executive coach benefit', 68),
  ('career', '40', '1 YEAR (Age 40)', 'Thought Leadership:', '2–3 AI conference speaking engagements', 69),
  ('career', '40', '1 YEAR (Age 40)', 'Thought Leadership:', 'LinkedIn to 7K+ followers', 70),
  ('career', '40', '1 YEAR (Age 40)', 'Thought Leadership:', '1–2 podcast appearances', 71),
  ('career', '40', '1 YEAR (Age 40)', 'Thought Leadership:', 'Build media relationships', 72),
  ('career', '40', '1 YEAR (Age 40)', 'Network:', 'Join 1–2 executive networks (YPO, Pavilion)', 73),
  ('career', '40', '1 YEAR (Age 40)', 'Network:', 'Expand network in AI and fintech', 74),
  ('career', '45', '5 YEARS (Age 45)', 'Role & Compensation:', 'SVP/EVP at Fortune 100 OR C-Suite at mid-size company', 75),
  ('career', '45', '5 YEARS (Age 45)', 'Role & Compensation:', 'Total comp: $500K–$1M', 76),
  ('career', '45', '5 YEARS (Age 45)', 'Role & Compensation:', '$100–200K in vested RSUs/equity', 77),
  ('career', '45', '5 YEARS (Age 45)', 'Thought Leadership:', '5+ keynotes/year', 78),
  ('career', '45', '5 YEARS (Age 45)', 'Thought Leadership:', 'TEDx talk completed', 79),
  ('career', '45', '5 YEARS (Age 45)', 'Thought Leadership:', 'Book in progress', 80),
  ('career', '45', '5 YEARS (Age 45)', 'Thought Leadership:', 'Featured in WSJ, Forbes, Fortune', 81),
  ('career', '45', '5 YEARS (Age 45)', 'Thought Leadership:', 'TV appearances (Fox Business, Bloomberg, CNBC)', 82),
  ('career', '45', '5 YEARS (Age 45)', 'Thought Leadership:', 'LinkedIn 25K+ followers', 83),
  ('career', '45', '5 YEARS (Age 45)', 'Network & Politics:', '50+ C-suite connections', 84),
  ('career', '45', '5 YEARS (Age 45)', 'Network & Politics:', 'Inner circle of 10 trusted advisors', 85),
  ('career', '45', '5 YEARS (Age 45)', 'Network & Politics:', 'Know local politicians, congressmen, senators', 86),
  ('career', '45', '5 YEARS (Age 45)', 'Network & Politics:', '5+ political fundraisers/year (Republican Party)', 87),
  ('career', '45', '5 YEARS (Age 45)', 'Boards:', '1–2 board seats (nonprofit/advisory/startup)', 88),
  ('career', '45', '5 YEARS (Age 45)', 'Boards:', '$25–50K/year board income', 89),
  ('career', '50', '10 YEARS (Age 50)', 'Role & Compensation:', 'C-Suite Fortune 500 (CIO/CDO/CAIO/CEO)', 90),
  ('career', '50', '10 YEARS (Age 50)', 'Role & Compensation:', 'Total comp: $1–3M+', 91),
  ('career', '50', '10 YEARS (Age 50)', 'Role & Compensation:', '$500K–$1M in vested RSUs/equity', 92),
  ('career', '50', '10 YEARS (Age 50)', 'Thought Leadership:', 'Book published (bestseller goal)', 93),
  ('career', '50', '10 YEARS (Age 50)', 'Thought Leadership:', 'Ring the bell on Wall Street', 94),
  ('career', '50', '10 YEARS (Age 50)', 'Thought Leadership:', 'Davos / World Economic Forum attendee', 95),
  ('career', '50', '10 YEARS (Age 50)', 'Thought Leadership:', 'Congress testimony on AI/tech', 96),
  ('career', '50', '10 YEARS (Age 50)', 'Thought Leadership:', 'Forbes/Fortune lists and covers', 97),
  ('career', '50', '10 YEARS (Age 50)', 'Thought Leadership:', 'Speaking fees $25–50K+', 98),
  ('career', '50', '10 YEARS (Age 50)', 'Network & Politics:', '100+ C-suite connections', 99),
  ('career', '50', '10 YEARS (Age 50)', 'Network & Politics:', 'Know governors, national figures', 100),
  ('career', '50', '10 YEARS (Age 50)', 'Network & Politics:', 'Major donor status; exploratory discussions about running', 101),
  ('career', '50', '10 YEARS (Age 50)', 'Boards:', '1–2 public company boards, 3–4 total', 102),
  ('career', '60', '20 YEARS (Age 60)', NULL, 'CEO / Board Portfolio / Political transition', 103),
  ('career', '60', '20 YEARS (Age 60)', NULL, 'Total comp: $3–5M (or $1M+ board income)', 104),
  ('career', '60', '20 YEARS (Age 60)', NULL, 'Speaking circuit $50–100K+ per appearance', 105),
  ('career', '60', '20 YEARS (Age 60)', NULL, 'Household name in business and politics', 106),
  ('career', '60', '20 YEARS (Age 60)', NULL, 'Inner circle of kingmakers and power brokers', 107),
  ('career', '60', '20 YEARS (Age 60)', NULL, 'Ready to run or in political career', 108),
  ('career', '60', '20 YEARS (Age 60)', NULL, '1+ Fortune 500 board seat, Chair of 1 board', 109),
  ('relationships', '40', '1 YEAR (Age 40)', NULL, 'Starting fresh — finding her through apps, matchmaker, friends, social circles', 110),
  ('relationships', '40', '1 YEAR (Age 40)', NULL, 'Looking for: values alignment, ambitious, fitness-oriented, family-oriented, wants kids', 111),
  ('relationships', '40', '1 YEAR (Age 40)', NULL, 'Engaged by 2026 (flexible) — definitely by 2028', 112),
  ('relationships', '40', '1 YEAR (Age 40)', NULL, 'Dream: Propose in Italy', 113),
  ('relationships', '40', '1 YEAR (Age 40)', NULL, 'Regular date nights, quality time, 1–2 trips together', 114),
  ('relationships', '40', '1 YEAR (Age 40)', NULL, 'Partner joins on business trips when possible', 115),
  ('relationships', '40', '1 YEAR (Age 40)', NULL, 'Come home to family dinners every night', 116),
  ('relationships', '45', '5 YEARS (Age 45)', NULL, 'Destination wedding in Italy (intimate gathering)', 117),
  ('relationships', '45', '5 YEARS (Age 45)', NULL, 'Honeymoon in Maldives', 118),
  ('relationships', '45', '5 YEARS (Age 45)', NULL, '2–3 kids by 45; done having kids by 45', 119),
  ('relationships', '45', '5 YEARS (Age 45)', NULL, 'Present, involved dad — coaching, quality time, teaching', 120),
  ('relationships', '45', '5 YEARS (Age 45)', NULL, 'Very strong marriage — divorce never an option', 121),
  ('relationships', '45', '5 YEARS (Age 45)', NULL, 'Weekly date nights, annual romantic trip (no kids)', 122),
  ('relationships', '45', '5 YEARS (Age 45)', NULL, 'Wife is stay-at-home if she chooses', 123),
  ('relationships', '45', '5 YEARS (Age 45)', NULL, 'Family joins on business trips often', 124),
  ('relationships', '45', '5 YEARS (Age 45)', NULL, 'Home: Dallas suburbs or bi-coastal Florida', 125),
  ('relationships', '50', '10 YEARS (Age 50)', NULL, 'Marriage stronger than ever, still madly in love, best friends', 126),
  ('relationships', '50', '10 YEARS (Age 50)', NULL, '10-year anniversary trip somewhere incredible', 127),
  ('relationships', '50', '10 YEARS (Age 50)', NULL, 'Kids (ages 5–12): private school, thriving in academics, sports, arts', 128),
  ('relationships', '50', '10 YEARS (Age 50)', NULL, 'Close family, quality time, lots of time with grandparents', 129),
  ('relationships', '50', '10 YEARS (Age 50)', NULL, 'Dream house with pool; 2nd or 3rd vacation home', 130),
  ('relationships', '60', '20 YEARS (Age 60)', NULL, 'Still traveling together, empty nest adventures', 131),
  ('relationships', '60', '20 YEARS (Age 60)', NULL, 'Wife comes on business trips', 132),
  ('relationships', '60', '20 YEARS (Age 60)', NULL, 'Kids (ages 15–22): attending top universities, well-adjusted, independent', 133),
  ('relationships', '60', '20 YEARS (Age 60)', NULL, 'Talk daily, visit at college monthly', 134),
  ('relationships', '60', '20 YEARS (Age 60)', NULL, 'Instilled: hard work, faith, integrity, ambition', 135),
  ('relationships', '60', '20 YEARS (Age 60)', NULL, 'Grandchildren post-60; very involved grandparent', 136),
  ('relationships', '60', '20 YEARS (Age 60)', NULL, 'Family compound near water or in Italy', 137),
  ('relationships', '60', '20 YEARS (Age 60)', NULL, '4–5 vacation homes; home base Florida or Texas', 138),
  ('family', '40', '1 YEAR (Age 40)', 'Parents:', 'See parents weekly if possible (dinner or quality time)', 139),
  ('family', '40', '1 YEAR (Age 40)', 'Parents:', 'Spend more intentional quality time with them', 140),
  ('family', '40', '1 YEAR (Age 40)', 'Parents:', 'Annual family trip together', 141),
  ('family', '40', '1 YEAR (Age 40)', 'Special Goal:', 'Restore a classic car with Dad — do this while he''s still here', 142),
  ('family', '40', '1 YEAR (Age 40)', 'Extended Family:', 'Talk to cousins once a month', 143),
  ('family', '40', '1 YEAR (Age 40)', 'Extended Family:', 'Visit Austin cousins quarterly', 144),
  ('family', '40', '1 YEAR (Age 40)', 'Extended Family:', 'Be more deliberate about staying connected', 145),
  ('family', '40', '1 YEAR (Age 40)', 'Extended Family:', 'Big cousin gathering once a year', 146),
  ('family', '40', '1 YEAR (Age 40)', 'Friendships:', 'Build tight inner circle in Dallas', 147),
  ('family', '40', '1 YEAR (Age 40)', 'Friendships:', 'Weekly or bi-weekly dinners (business ideas, ventures, investments)', 148),
  ('family', '40', '1 YEAR (Age 40)', 'Friendships:', 'Visit lifetime best friends at least once this year', 149),
  ('family', '40', '1 YEAR (Age 40)', 'Community:', 'Volunteer more', 150),
  ('family', '40', '1 YEAR (Age 40)', 'Community:', 'Join 1–2 volunteer groups or nonprofits', 151),
  ('family', '45', '5 YEARS (Age 45)', 'Parents:', 'See weekly or twice a week', 152),
  ('family', '45', '5 YEARS (Age 45)', 'Parents:', 'Lots of time with parents and kids together', 153),
  ('family', '45', '5 YEARS (Age 45)', 'Parents:', 'Kids spend plenty of time with both sets of grandparents', 154),
  ('family', '45', '5 YEARS (Age 45)', 'Extended Family:', 'Same cadence (monthly calls, quarterly visits)', 155),
  ('family', '45', '5 YEARS (Age 45)', 'Extended Family:', 'Family gatherings twice a year now that kids are in picture', 156),
  ('family', '45', '5 YEARS (Age 45)', 'Friendships:', 'Inner circle of 8–12 top quality friends in Dallas', 157),
  ('family', '45', '5 YEARS (Age 45)', 'Friendships:', 'Annual trip with lifetime best friends', 158),
  ('family', '45', '5 YEARS (Age 45)', 'Friendships:', 'More frequent get-togethers', 159),
  ('family', '45', '5 YEARS (Age 45)', 'Community & Philanthropy:', 'Bigger involvement', 160),
  ('family', '45', '5 YEARS (Age 45)', 'Community & Philanthropy:', 'Board seat on 1 nonprofit', 161),
  ('family', '45', '5 YEARS (Age 45)', 'Community & Philanthropy:', 'Begin thinking about starting a foundation', 162),
  ('family', '50', '10 YEARS (Age 50)', 'Parents (ages ~85–87):', 'Spend lots of quality time while still here', 163),
  ('family', '50', '10 YEARS (Age 50)', 'Parents (ages ~85–87):', 'Big annual trip with parents, wife, and kids — see the world together', 164),
  ('family', '50', '10 YEARS (Age 50)', 'Parents (ages ~85–87):', 'Cherish every moment', 165),
  ('family', '50', '10 YEARS (Age 50)', 'Extended Family:', 'Tighter than ever', 166),
  ('family', '50', '10 YEARS (Age 50)', 'Extended Family:', 'Big family trips with both sides 1–2x/year', 167),
  ('family', '50', '10 YEARS (Age 50)', 'Friendships:', 'Inner circle grown to 15–20 globally (not just Dallas)', 168),
  ('family', '50', '10 YEARS (Age 50)', 'Philanthropy:', 'Foundation started (stretch goal)', 169),
  ('family', '50', '10 YEARS (Age 50)', 'Philanthropy:', 'Major donor / active in multiple charities', 170),
  ('family', '50', '10 YEARS (Age 50)', 'Philanthropy:', 'Focus areas: Children and cancer-related causes', 171),
  ('family', '60', '20 YEARS (Age 60)', 'Honor Parents'' Memory & Legacy:', 'Name something after them (scholarship, foundation wing, building)', 172),
  ('family', '60', '20 YEARS (Age 60)', 'Honor Parents'' Memory & Legacy:', 'Annual family tradition to celebrate their lives', 173),
  ('family', '60', '20 YEARS (Age 60)', 'Honor Parents'' Memory & Legacy:', 'Philanthropy in their name', 174),
  ('family', '60', '20 YEARS (Age 60)', 'Honor Parents'' Memory & Legacy:', 'Legacy book or video documenting their story', 175),
  ('family', '60', '20 YEARS (Age 60)', 'Honor Parents'' Memory & Legacy:', 'Endowed scholarship', 176),
  ('family', '60', '20 YEARS (Age 60)', 'Honor Parents'' Memory & Legacy:', 'Family foundation named after them', 177),
  ('family', '60', '20 YEARS (Age 60)', 'Extended Family:', 'The one who brings everyone together', 178),
  ('family', '60', '20 YEARS (Age 60)', 'Extended Family:', 'Organizes and plans family trips and gatherings', 179),
  ('family', '60', '20 YEARS (Age 60)', 'Extended Family:', 'Patriarch role', 180),
  ('family', '60', '20 YEARS (Age 60)', 'Friendships:', 'Global circle of ~30 close-knit, successful, ambitious, like-minded individuals', 181),
  ('family', '60', '20 YEARS (Age 60)', 'Philanthropy:', 'Foundation grown significantly', 182),
  ('family', '60', '20 YEARS (Age 60)', 'Philanthropy:', 'Causes: Anti-bullying (personal), children with disabilities/alternative learning, cancer, children''s causes', 183),
  ('family', '60', '20 YEARS (Age 60)', 'Philanthropy:', '$500K–$1M/year philanthropic giving', 184),
  ('finance', '40', '1 YEAR (Age 40)', 'Income:', 'Total comp: $300–400K (base $230–260K)', 185),
  ('finance', '40', '1 YEAR (Age 40)', 'Income:', 'Negotiate sign-on bonus $50–100K', 186),
  ('finance', '40', '1 YEAR (Age 40)', 'Net Worth:', 'Current: ~$370K', 187),
  ('finance', '40', '1 YEAR (Age 40)', 'Net Worth:', 'Target: $450–500K', 188),
  ('finance', '40', '1 YEAR (Age 40)', '401K:', 'Target: $230K', 189),
  ('finance', '40', '1 YEAR (Age 40)', '401K:', 'Max out contributions with new job', 190),
  ('finance', '40', '1 YEAR (Age 40)', '401K:', 'Maximize employer match from Day 1', 191),
  ('finance', '40', '1 YEAR (Age 40)', 'Brokerage:', 'Restart with $10K', 192),
  ('finance', '40', '1 YEAR (Age 40)', 'Emergency Fund:', 'Rebuild to 6 months expenses', 193),
  ('finance', '40', '1 YEAR (Age 40)', 'Debt:', 'Consolidate $150K into HELOC', 194),
  ('finance', '40', '1 YEAR (Age 40)', 'Debt:', 'Pay down aggressively, free up cash flow', 195),
  ('finance', '40', '1 YEAR (Age 40)', 'Real Estate:', 'Stay in current townhome', 196),
  ('finance', '40', '1 YEAR (Age 40)', 'Real Estate:', 'Goal: Turn into rental eventually', 197),
  ('finance', '40', '1 YEAR (Age 40)', 'Real Estate:', 'Begin exploring vacation homes in Florida', 198),
  ('finance', '45', '5 YEARS (Age 45)', 'Income:', 'Total comp: $500K–$1M', 199),
  ('finance', '45', '5 YEARS (Age 45)', 'Income:', 'Board income: $25–50K/year', 200),
  ('finance', '45', '5 YEARS (Age 45)', 'Net Worth:', 'Target: $2–2.5M', 201),
  ('finance', '45', '5 YEARS (Age 45)', 'Investments:', '401K: $600K', 202),
  ('finance', '45', '5 YEARS (Age 45)', 'Investments:', 'Brokerage: $200–250K', 203),
  ('finance', '45', '5 YEARS (Age 45)', 'Investments:', 'Equity/RSUs: $100–200K vested', 204),
  ('finance', '45', '5 YEARS (Age 45)', 'Real Estate:', '2 properties (main home + townhome as rental)', 205),
  ('finance', '45', '5 YEARS (Age 45)', 'Real Estate:', 'Fully debt-free', 206),
  ('finance', '50', '10 YEARS (Age 50)', 'Income:', 'Total comp: $1–3M+', 207),
  ('finance', '50', '10 YEARS (Age 50)', 'Net Worth:', 'Target: $6–8M', 208),
  ('finance', '50', '10 YEARS (Age 50)', 'Investments:', '401K: $1.3M', 209),
  ('finance', '50', '10 YEARS (Age 50)', 'Investments:', 'Brokerage: $750K–$1M', 210),
  ('finance', '50', '10 YEARS (Age 50)', 'Investments:', 'Equity/RSUs: $500K–$1M vested', 211),
  ('finance', '50', '10 YEARS (Age 50)', 'Investments:', 'Real estate equity: $1.5–2M', 212),
  ('finance', '50', '10 YEARS (Age 50)', 'Passive Income ($10–15K/month):', 'Rental income: $2–3K/month', 213),
  ('finance', '50', '10 YEARS (Age 50)', 'Passive Income ($10–15K/month):', 'Board seats (2–3): $4–6K/month', 214),
  ('finance', '50', '10 YEARS (Age 50)', 'Passive Income ($10–15K/month):', 'Speaking (6–10/year): $2–4K/month', 215),
  ('finance', '50', '10 YEARS (Age 50)', 'Passive Income ($10–15K/month):', 'Book royalties/consulting: $1–2K/month', 216),
  ('finance', '50', '10 YEARS (Age 50)', 'Passive Income ($10–15K/month):', 'Dividends: $1–2K/month', 217),
  ('finance', '60', '20 YEARS (Age 60)', 'Income:', 'Total comp: $3–5M (or $1M+ board income if retired)', 218),
  ('finance', '60', '20 YEARS (Age 60)', 'Net Worth:', 'Target: $15–25M', 219),
  ('finance', '60', '20 YEARS (Age 60)', 'Investments:', '401K: $5M+', 220),
  ('finance', '60', '20 YEARS (Age 60)', 'Investments:', 'Brokerage: $2–5M', 221),
  ('finance', '60', '20 YEARS (Age 60)', 'Investments:', 'Real estate equity: $5M+', 222),
  ('finance', '60', '20 YEARS (Age 60)', 'Passive Income ($25–50K/month):', 'Board income (3 boards): $10–15K/month', 223),
  ('finance', '60', '20 YEARS (Age 60)', 'Passive Income ($25–50K/month):', 'Rental income (2–3 properties): $5–8K/month', 224),
  ('finance', '60', '20 YEARS (Age 60)', 'Passive Income ($25–50K/month):', 'Speaking (10–15/year @ $50–100K): $5–10K/month', 225),
  ('finance', '60', '20 YEARS (Age 60)', 'Passive Income ($25–50K/month):', 'Investment dividends: $3–5K/month', 226),
  ('finance', '60', '20 YEARS (Age 60)', 'Passive Income ($25–50K/month):', 'Book royalties/IP: $1–2K/month', 227),
  ('finance', '60', '20 YEARS (Age 60)', 'Passive Income ($25–50K/month):', 'Consulting/advisory: $2–5K/month', 228),
  ('home', '40', '1 YEAR (Age 40) — Current Townhome', NULL, 'Furnish rooftop deck', 229),
  ('home', '40', '1 YEAR (Age 40) — Current Townhome', NULL, 'Furnish patio', 230),
  ('home', '40', '1 YEAR (Age 40) — Current Townhome', NULL, 'Finish decorating and furnishing current townhome', 231),
  ('home', '40', '1 YEAR (Age 40) — Current Townhome', NULL, 'Optimize current home theater', 232),
  ('home', '45', '5 YEARS (Age 45) — First Major Home Upgrade', NULL, 'Large home with pool', 233),
  ('home', '45', '5 YEARS (Age 45) — First Major Home Upgrade', NULL, 'Home gym', 234),
  ('home', '45', '5 YEARS (Age 45) — First Major Home Upgrade', NULL, 'Lego room', 235),
  ('home', '45', '5 YEARS (Age 45) — First Major Home Upgrade', NULL, 'Wine cellar (starter)', 236),
  ('home', '45', '5 YEARS (Age 45) — First Major Home Upgrade', NULL, 'Home theater — dedicated room', 237),
  ('home', '45', '5 YEARS (Age 45) — First Major Home Upgrade', NULL, 'Outdoor kitchen with pizza oven & grill', 238),
  ('home', '45', '5 YEARS (Age 45) — First Major Home Upgrade', NULL, 'Smart home — fully automated', 239),
  ('home', '45', '5 YEARS (Age 45) — First Major Home Upgrade', NULL, 'Home office with views', 240),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Master Suite:', 'His and hers walk-in closets (custom built)', 241),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Master Suite:', 'Dual shower (spa-style)', 242),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Master Suite:', 'Spa-style master bathroom with soaking tub', 243),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Master Suite:', 'Fireplace in master bedroom', 244),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Master Suite:', 'Private balcony off master', 245),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Master Suite:', 'Morning kitchen / coffee bar in master suite', 246),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Kitchen & Dining:', 'Chef''s kitchen with professional appliances (Wolf, Sub-Zero, etc.)', 247),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Kitchen & Dining:', 'Butler''s pantry', 248),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Kitchen & Dining:', 'Formal dining room for hosting dinner parties', 249),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Living & Entertainment:', 'Great room with soaring ceilings', 250),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Living & Entertainment:', 'Home theater / media room (dedicated)', 251),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Living & Entertainment:', 'Library / study with built-in bookshelves', 252),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Living & Entertainment:', 'Game room (poker table, billiards, arcade)', 253),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Living & Entertainment:', 'Music room / listening room', 254),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Living & Entertainment:', 'Bar area (wet bar or full bar)', 255),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Living & Entertainment:', 'Cigar lounge or whiskey room', 256),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Living & Entertainment:', 'Lego room', 257),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Living & Entertainment:', 'Arts & crafts room', 258),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Wellness & Fitness:', 'Home gym', 259),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Wellness & Fitness:', 'Sauna / steam room', 260),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Outdoor Living:', 'Large yard with pool (indoor/outdoor with spa)', 261),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Outdoor Living:', 'Hot tub / jacuzzi separate from pool', 262),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Outdoor Living:', 'Outdoor kitchen with pizza oven & grill', 263),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Outdoor Living:', 'Outdoor fireplace / fire pit', 264),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Outdoor Living:', 'Cabana or pool house', 265),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Outdoor Living:', 'Sport court (basketball, pickleball)', 266),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Outdoor Living:', 'Bocce ball court', 267),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Outdoor Living:', 'Putting green', 268),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Outdoor Living:', 'Outdoor shower', 269),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Outdoor Living:', 'Landscaped gardens / water features', 270),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Outdoor Living:', 'Rooftop deck or terrace', 271),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Functional & Tech:', 'Wine cellar (temperature-controlled)', 272),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Functional & Tech:', 'Car garage / showroom for collection', 273),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Functional & Tech:', 'Guest house for family visits', 274),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Functional & Tech:', 'Whole-home audio system (Sonos, etc.)', 275),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Functional & Tech:', 'Integrated security system with cameras', 276),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Functional & Tech:', 'Automated lighting, shades, and climate control', 277),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Functional & Tech:', 'Voice-controlled everything', 278),
  ('home', '50', '10 YEARS (Age 50) — Dream Home', 'Functional & Tech:', 'Dedicated server room / networking closet', 279),
  ('home', '60', '20 YEARS (Age 60) — Legacy Home', NULL, 'All Age 50 features plus:', 280),
  ('home', '60', '20 YEARS (Age 60) — Legacy Home', NULL, 'Indoor gun range', 281),
  ('home', '60', '20 YEARS (Age 60) — Legacy Home', NULL, '4–5 properties total', 282),
  ('home', '60', '20 YEARS (Age 60) — Legacy Home', NULL, 'Family compound near water or in Italy', 283),
  ('home', '60', '20 YEARS (Age 60) — Legacy Home', NULL, 'Full car collection showroom', 284),
  ('home', '60', '20 YEARS (Age 60) — Legacy Home', NULL, 'Staff quarters if needed', 285),
  ('fun', '40', '1 YEAR (Age 40) — Ideal Weekend', NULL, 'Early morning workout', 286),
  ('fun', '40', '1 YEAR (Age 40) — Ideal Weekend', NULL, 'Brunch with friends or family', 287),
  ('fun', '40', '1 YEAR (Age 40) — Ideal Weekend', NULL, 'Afternoon at country club (tennis or pool)', 288),
  ('fun', '40', '1 YEAR (Age 40) — Ideal Weekend', NULL, 'Dinner out with family or friends', 289),
  ('fun', '40', '1 YEAR (Age 40) — Ideal Weekend', NULL, 'Evening: live concert/music OR relaxing night at home with wine and grilling', 290),
  ('fun', '45', '5 YEARS (Age 45) — Ideal Weekend (With Family)', NULL, 'Morning workout or family activity', 291),
  ('fun', '45', '5 YEARS (Age 45) — Ideal Weekend (With Family)', NULL, 'Day at beach, park, pool, or boating', 292),
  ('fun', '45', '5 YEARS (Age 45) — Ideal Weekend (With Family)', NULL, 'Family dinner or BBQ', 293),
  ('fun', '45', '5 YEARS (Age 45) — Ideal Weekend (With Family)', NULL, 'Time at country club', 294),
  ('fun', '45', '5 YEARS (Age 45) — Ideal Weekend (With Family)', NULL, 'Relaxing together — quality time over everything', 295),
  ('fun', '50', '10 YEARS (Age 50) — Ideal Weekend', NULL, 'Morning golf or tennis', 296),
  ('fun', '50', '10 YEARS (Age 50) — Ideal Weekend', NULL, 'Family time at vacation home', 297),
  ('fun', '50', '10 YEARS (Age 50) — Ideal Weekend', NULL, 'Hosting friends and family for a dinner party', 298),
  ('fun', '50', '10 YEARS (Age 50) — Ideal Weekend', NULL, 'Wine from the cellar, home-cooked gourmet meal', 299),
  ('fun', '60', '20 YEARS (Age 60) — Ideal Weekend', NULL, 'Golf or tennis with friends or grandkids', 300),
  ('fun', '60', '20 YEARS (Age 60) — Ideal Weekend', NULL, 'Boating or relaxing at family compound', 301),
  ('fun', '60', '20 YEARS (Age 60) — Ideal Weekend', NULL, 'Multi-generational gatherings — the patriarch hosting everyone', 302),
  ('fun', '60', '20 YEARS (Age 60) — Ideal Weekend', NULL, 'Enjoying the life that was built', 303),
  ('fun', 'pinned', 'TOP 5 BUCKET LIST TRIPS', NULL, 'SE Asia — Thailand, Vietnam, Indonesia, Cambodia', 304),
  ('fun', 'pinned', 'TOP 5 BUCKET LIST TRIPS', NULL, 'Egypt — Pyramids, Nile, ancient history', 305),
  ('fun', 'pinned', 'TOP 5 BUCKET LIST TRIPS', NULL, 'Machu Picchu — Hike the Inca Trail', 306),
  ('fun', 'pinned', 'TOP 5 BUCKET LIST TRIPS', NULL, 'Viking River Cruise — France & Germany with parents', 307),
  ('fun', 'pinned', 'TOP 5 BUCKET LIST TRIPS', NULL, 'African Safari — Kenya, Tanzania, or South Africa', 308),
  ('fun', 'all', 'Collecting', 'Watches:', 'Currently: Rolex collection', 309),
  ('fun', 'all', 'Collecting', 'Watches:', 'By 50: Add Audemars Piguet (AP) and Patek Philippe', 310),
  ('fun', 'all', 'Collecting', 'Cars:', 'Near-term: Porsche 911 + G-Wagon or Range Rover', 311),
  ('fun', 'all', 'Collecting', 'Cars:', 'Mid-term: Porsche Panamera + Ferrari (dream car)', 312),
  ('fun', 'all', 'Collecting', 'Cars:', 'Long-term: Classic car collection', 313),
  ('fun', 'all', 'Collecting', 'Wine:', 'Begin collecting from age 40 onward', 314),
  ('fun', 'all', 'Collecting', 'Wine:', 'Build a curated cellar', 315),
  ('fun', 'all', 'Collecting', 'Art:', 'Mix of paintings, glass, and sculptures', 316),
  ('fun', 'all', 'Collecting', 'Art:', 'Goal to own originals; build collection ages 40–60', 317),
  ('fun', 'all', 'Collecting', 'Legos:', 'Continue collecting UCS sets', 318),
  ('fun', 'all', 'Collecting', 'Legos:', 'Dedicated Lego room in dream home', 319),
  ('fun', 'all', 'Hobbies', 'Current (Age 40):', 'Cooking (Italian, gourmet)', 320),
  ('fun', 'all', 'Hobbies', 'Current (Age 40):', 'Fitness / strength training', 321),
  ('fun', 'all', 'Hobbies', 'Current (Age 40):', 'Travel', 322),
  ('fun', 'all', 'Hobbies', 'Current (Age 40):', 'Building Legos', 323),
  ('fun', 'all', 'Hobbies', 'Current (Age 40):', 'Entertaining / hosting', 324),
  ('fun', 'all', 'Hobbies', 'Current (Age 40):', 'Gaming', 325),
  ('fun', 'all', 'Hobbies', 'Pick Up (Ages 40–45):', 'Golf', 326),
  ('fun', 'all', 'Hobbies', 'Pick Up (Ages 40–45):', 'Tennis', 327),
  ('fun', 'all', 'Hobbies', 'Pick Up (Ages 40–45):', 'Cycling', 328),
  ('fun', 'all', 'Hobbies', 'Pick Up (Ages 40–45):', 'Wine appreciation and collecting', 329),
  ('fun', 'all', 'Hobbies', 'Pick Up (Ages 40–45):', 'Art collecting', 330),
  ('fun', 'all', 'Hobbies', 'Continue & Add (Ages 45–60):', 'Skiing', 331),
  ('fun', 'all', 'Hobbies', 'Continue & Add (Ages 45–60):', 'Hiking', 332),
  ('fun', 'all', 'Hobbies', 'Continue & Add (Ages 45–60):', 'Krav Maga / tactical shooting', 333),
  ('fun', 'all', 'Hobbies', 'Continue & Add (Ages 45–60):', 'Boating', 334),
  ('fun', 'all', 'Hobbies', 'Continue & Add (Ages 45–60):', 'Watch collecting', 335),
  ('fun', 'all', 'Hobbies', 'Continue & Add (Ages 45–60):', 'Car collecting', 336),
  ('fun', 'all', 'Experiences & Bucket List', 'Travel & Adventure:', 'Charter a yacht for a family vacation', 337),
  ('fun', 'all', 'Experiences & Bucket List', 'Travel & Adventure:', 'Rent a villa in Italy for extended family', 338),
  ('fun', 'all', 'Experiences & Bucket List', 'Travel & Adventure:', 'Helicopter tour experiences', 339),
  ('fun', 'all', 'Experiences & Bucket List', 'Travel & Adventure:', 'Learn to sail', 340),
  ('fun', 'all', 'Experiences & Bucket List', 'Travel & Adventure:', 'Race a car on a track (Porsche Experience)', 341),
  ('fun', 'all', 'Experiences & Bucket List', 'Travel & Adventure:', 'Get pilot''s license (stretch goal)', 342),
  ('fun', 'all', 'Experiences & Bucket List', 'Hosting & Entertaining:', 'Host an annual dinner party / gala at home', 343),
  ('fun', 'all', 'Experiences & Bucket List', 'Hosting & Entertaining:', 'Host holiday gatherings as a family tradition', 344),
  ('fun', 'all', 'Experiences & Bucket List', 'Hosting & Entertaining:', 'Private chef dinner parties at home', 345),
  ('fun', 'all', 'Experiences & Bucket List', 'Hosting & Entertaining:', 'Michelin restaurant bucket list tour', 346),
  ('fun', 'all', 'Experiences & Bucket List', 'Sports & Signature Events:', 'F1 Monaco Grand Prix (PRIORITY)', 347),
  ('fun', 'all', 'Experiences & Bucket List', 'Sports & Signature Events:', 'Super Bowl', 348),
  ('fun', 'all', 'Experiences & Bucket List', 'Sports & Signature Events:', 'The Masters', 349),
  ('fun', 'all', 'Experiences & Bucket List', 'Sports & Signature Events:', 'US Open Tennis (NYC)', 350),
  ('fun', 'all', 'Experiences & Bucket List', 'Sports & Signature Events:', 'Kentucky Derby', 351),
  ('fun', 'all', 'Experiences & Bucket List', 'Sports & Signature Events:', 'Cowboys & Stars box seats', 352),
  ('fun', 'all', 'Experiences & Bucket List', 'Sports & Signature Events:', 'VIP concerts and festival experiences', 353),
  ('memberships', '40', '1 YEAR (Age 40)', NULL, 'Life Time Fitness (current)', 354),
  ('memberships', '40', '1 YEAR (Age 40)', NULL, 'Recovery clinic membership (cryo, sauna, cold plunge)', 355),
  ('memberships', '40', '1 YEAR (Age 40)', NULL, 'Spa membership', 356),
  ('memberships', '40', '1 YEAR (Age 40)', NULL, 'Amex Fine Hotels & Resorts (current)', 357),
  ('memberships', '40', '1 YEAR (Age 40)', NULL, 'Research and establish Virtuoso travel advisor relationship', 358),
  ('memberships', '40', '1 YEAR (Age 40)', NULL, 'Country club membership', 359),
  ('memberships', '45', '5 YEARS (Age 45)', NULL, 'Country club established', 360),
  ('memberships', '45', '5 YEARS (Age 45)', NULL, 'Golf club (prestigious course)', 361),
  ('memberships', '45', '5 YEARS (Age 45)', NULL, 'Social clubs (Soho House, private members clubs)', 362),
  ('memberships', '45', '5 YEARS (Age 45)', NULL, 'Wine club memberships (Napa, Tuscany)', 363),
  ('memberships', '45', '5 YEARS (Age 45)', NULL, 'Cigar club / whiskey society', 364),
  ('memberships', '45', '5 YEARS (Age 45)', NULL, 'Box seats: Dallas Cowboys & Dallas Stars', 365),
  ('memberships', '45', '5 YEARS (Age 45)', NULL, 'VIP concert and festival access', 366),
  ('memberships', '45', '5 YEARS (Age 45)', NULL, 'Art gallery / museum patron', 367),
  ('memberships', '45', '5 YEARS (Age 45)', NULL, 'Theater and symphony patron', 368),
  ('memberships', '45', '5 YEARS (Age 45)', NULL, 'Charity galas and fundraiser circuit', 369),
  ('memberships', '50', '10 YEARS (Age 50)', NULL, 'Yacht club membership', 370),
  ('memberships', '50', '10 YEARS (Age 50)', NULL, 'Private aviation membership (NetJets, Wheels Up)', 371),
  ('memberships', '50', '10 YEARS (Age 50)', NULL, 'Charter a yacht with family', 372),
  ('memberships', '50', '10 YEARS (Age 50)', NULL, 'Virtuoso travel advisor — established long-term relationship', 373),
  ('memberships', '50', '10 YEARS (Age 50)', NULL, 'Active on charity gala circuit', 374),
  ('memberships', '50', '10 YEARS (Age 50)', NULL, 'Political donor circles (Republican Party)', 375),
  ('memberships', '60', '20 YEARS (Age 60)', NULL, 'All memberships maintained', 376),
  ('memberships', '60', '20 YEARS (Age 60)', NULL, 'Elite / invite-only clubs (Bohemian Grove, Alfalfa Club level)', 377),
  ('memberships', '60', '20 YEARS (Age 60)', NULL, 'Davos / World Economic Forum access', 378),
  ('memberships', '60', '20 YEARS (Age 60)', NULL, 'Major political donor status', 379),
  ('personal-dev', '40', '1 YEAR (Age 40)', 'Education & Credentials:', 'Complete MIT Sloan: AI — Implications for Business Strategy (6-week online)', 380),
  ('personal-dev', '40', '1 YEAR (Age 40)', 'Education & Credentials:', 'Enroll in Wharton: Generative AI & Business Transformation (in-person executive program)', 381),
  ('personal-dev', '40', '1 YEAR (Age 40)', 'Education & Credentials:', 'Begin structured Spanish learning (Pimsleur + iTalki tutor)', 382),
  ('personal-dev', '40', '1 YEAR (Age 40)', 'Education & Credentials:', 'Begin Italian — conversational basics for travel', 383),
  ('personal-dev', '40', '1 YEAR (Age 40)', 'Communication & Leadership:', 'Complete public speaking training (formal program)', 384),
  ('personal-dev', '40', '1 YEAR (Age 40)', 'Communication & Leadership:', 'Deliver first keynote at an industry event', 385),
  ('personal-dev', '40', '1 YEAR (Age 40)', 'Communication & Leadership:', 'Complete EQ assessment; begin structured executive coaching on vulnerability & trust', 386),
  ('personal-dev', '40', '1 YEAR (Age 40)', 'Communication & Leadership:', 'Complete structured negotiation training (Harvard PON or equivalent)', 387),
  ('personal-dev', '40', '1 YEAR (Age 40)', 'Reading & Intellect:', 'Read 12 books/year minimum — leadership, AI, philosophy, stoicism', 388),
  ('personal-dev', '40', '1 YEAR (Age 40)', 'Reading & Intellect:', 'Start a consistent reading habit with notes/reflection', 389),
  ('personal-dev', '40', '1 YEAR (Age 40)', 'Personal Growth:', 'Active therapy or executive coaching', 390),
  ('personal-dev', '40', '1 YEAR (Age 40)', 'Personal Growth:', 'Working on vulnerability, emotional openness, and presence', 391),
  ('personal-dev', '40', '1 YEAR (Age 40)', 'Personal Growth:', 'Annual silent retreat or leadership immersive — 5–7 days of disconnection and reset', 392),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Education & Credentials:', 'Enrolled in or completing MIT Sloan Executive MBA (#1 globally ranked, FT 2026)', 393),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Education & Credentials:', 'Harvard Kennedy School: Emerging Leaders completed (Age 42–43)', 394),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Education & Credentials:', 'Harvard Kennedy School: Leadership for the 21st Century (Age 45–46)', 395),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Education & Credentials:', 'NACD Board Leadership Fellow — Fortune 500 board readiness credential (Age 46)', 396),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Education & Credentials:', 'Conversational Spanish — using in professional and social contexts in Dallas', 397),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Education & Credentials:', 'Conversational Italian — using during Italy trips and with family', 398),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Communication & Leadership:', 'Deliver TEDx talk or major conference keynote', 399),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Communication & Leadership:', 'Leading 100+ person organization with measurable culture results', 400),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Communication & Leadership:', 'Mentor 3+ rising leaders formally', 401),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Communication & Leadership:', 'Applying negotiation skills in M&A, board, and policy contexts', 402),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Reading & Writing:', 'Deep reading in policy, history, theology', 403),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Reading & Writing:', 'First draft of own book in progress', 404),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Reading & Writing:', 'Reading list curated and shared with inner circle', 405),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Personal Growth:', 'Measurable growth in EQ, presence, and work-life integration', 406),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Personal Growth:', 'Fully present with partner and growing family', 407),
  ('personal-dev', '45', '5 YEARS (Age 45)', 'Personal Growth:', 'Annual leadership immersive or silent retreat maintained', 408),
  ('personal-dev', '50', '10 YEARS (Age 50)', 'Education & Credentials:', 'MIT Sloan Executive MBA complete', 409),
  ('personal-dev', '50', '10 YEARS (Age 50)', 'Education & Credentials:', 'Harvard Kennedy School: Technology & Public Leadership Certificate earned (requires 3 HKS programs)', 410),
  ('personal-dev', '50', '10 YEARS (Age 50)', 'Education & Credentials:', 'Full credential stack established: MBA + HKS + NACD + MIT/Wharton programs', 411),
  ('personal-dev', '50', '10 YEARS (Age 50)', 'Education & Credentials:', 'Business-level Spanish fluency — fully integrated', 412),
  ('personal-dev', '50', '10 YEARS (Age 50)', 'Education & Credentials:', 'Comfortable Italian across social and travel contexts', 413),
  ('personal-dev', '50', '10 YEARS (Age 50)', 'Communication & Leadership:', 'Speak at TED main stage or equivalent global platform', 414),
  ('personal-dev', '50', '10 YEARS (Age 50)', 'Communication & Leadership:', 'Published author — book on AI-driven business transformation', 415),
  ('personal-dev', '50', '10 YEARS (Age 50)', 'Communication & Leadership:', 'Recognized as transformational leader; C-suite with board experience', 416),
  ('personal-dev', '50', '10 YEARS (Age 50)', 'Communication & Leadership:', 'Expert-level negotiator — government and cross-sector deals', 417),
  ('personal-dev', '50', '10 YEARS (Age 50)', 'Bucket List Growth Experiences:', 'Attend World Economic Forum at Davos', 418),
  ('personal-dev', '50', '10 YEARS (Age 50)', 'Bucket List Growth Experiences:', 'Complete a silent retreat or leadership immersive (annual)', 419),
  ('personal-dev', '50', '10 YEARS (Age 50)', 'Bucket List Growth Experiences:', 'Speak at a major global conference — sharing the AI transformation story', 420),
  ('personal-dev', '50', '10 YEARS (Age 50)', 'Personal Growth:', 'Fully integrated — professional excellence and personal wholeness aligned', 421),
  ('personal-dev', '50', '10 YEARS (Age 50)', 'Personal Growth:', 'Work-life integration mastered — present as father, husband, and leader', 422),
  ('personal-dev', '50', '10 YEARS (Age 50)', 'Personal Growth:', 'Trusting team, faith, and process — released need to control everything', 423),
  ('personal-dev', '60', '20 YEARS (Age 60)', 'Credentials & Legacy:', 'Recognized thought leader with full credential stack', 424),
  ('personal-dev', '60', '20 YEARS (Age 60)', 'Credentials & Legacy:', 'Mentoring the next generation of executives and leaders', 425),
  ('personal-dev', '60', '20 YEARS (Age 60)', 'Credentials & Legacy:', 'Pilgrimage to the Holy Land / Jerusalem — the journey of a lifetime', 426),
  ('personal-dev', '60', '20 YEARS (Age 60)', 'Credentials & Legacy:', 'Intellectual legacy — curating reading lists and ideas for others', 427),
  ('personal-dev', '60', '20 YEARS (Age 60)', 'Communication & Influence:', 'Known as a world-class communicator — regular global keynote speaker', 428),
  ('personal-dev', '60', '20 YEARS (Age 60)', 'Communication & Influence:', 'Speaking fees $50–100K+ per appearance', 429),
  ('personal-dev', '60', '20 YEARS (Age 60)', 'Communication & Influence:', 'Multi-book author; possible second book on leadership or public service', 430),
  ('personal-dev', '60', '20 YEARS (Age 60)', 'Communication & Influence:', 'Household name in business, AI, and political circles', 431),
  ('personal-dev', '60', '20 YEARS (Age 60)', 'Languages:', 'Bilingual — Spanish fully integrated into daily life', 432),
  ('personal-dev', '60', '20 YEARS (Age 60)', 'Languages:', 'Working Italian proficiency — speaking it at the family compound in Italy', 433),
  ('personal-dev', '60', '20 YEARS (Age 60)', 'Personal Growth:', 'At peace — wisdom earned from a full life; giving it back freely', 434),
  ('personal-dev', '60', '20 YEARS (Age 60)', 'Personal Growth:', 'Multi-organization legacy; shaping leadership in business and public life', 435),
  ('personal-dev', '60', '20 YEARS (Age 60)', 'Personal Growth:', 'A man who grew into everything he set out to become — and more', 436),
  ('spiritual', '40', '1 YEAR (Age 40)', 'Church & Community:', 'Find a Catholic parish in Dallas — attend regularly', 437),
  ('spiritual', '40', '1 YEAR (Age 40)', 'Church & Community:', 'Begin introducing myself to the community; get connected', 438),
  ('spiritual', '40', '1 YEAR (Age 40)', 'Church & Community:', 'Volunteer in one area of ministry', 439),
  ('spiritual', '40', '1 YEAR (Age 40)', 'Daily Practice:', 'Establish consistent daily prayer and morning devotional habit', 440),
  ('spiritual', '40', '1 YEAR (Age 40)', 'Daily Practice:', 'Regular Mass attendance — weekly commitment', 441),
  ('spiritual', '40', '1 YEAR (Age 40)', 'Daily Practice:', 'Meditation and quiet reflection — creating space to listen, not just speak', 442),
  ('spiritual', '40', '1 YEAR (Age 40)', 'Faith & Giving:', 'Begin consistent tithing — establish a giving habit tied to faith', 443),
  ('spiritual', '40', '1 YEAR (Age 40)', 'Spiritual Milestones:', 'First annual spiritual retreat or renewal weekend — away from screens and noise', 444),
  ('spiritual', '40', '1 YEAR (Age 40)', 'Spiritual Milestones:', 'Time to sit with God, review the year, and return to who I am meant to be', 445),
  ('spiritual', '45', '5 YEARS (Age 45)', 'Church & Community:', 'Active, committed parish member — known by name, part of the community fabric', 446),
  ('spiritual', '45', '5 YEARS (Age 45)', 'Church & Community:', 'Serving in ministry consistently', 447),
  ('spiritual', '45', '5 YEARS (Age 45)', 'Church & Community:', 'Connected with a faith-based community beyond Sunday', 448),
  ('spiritual', '45', '5 YEARS (Age 45)', 'Faith in Family Life:', 'Raising children with Catholic faith as a foundation', 449),
  ('spiritual', '45', '5 YEARS (Age 45)', 'Faith in Family Life:', 'Family Mass attendance as a non-negotiable tradition', 450),
  ('spiritual', '45', '5 YEARS (Age 45)', 'Faith in Family Life:', 'Very strong marriage rooted in shared faith — praying together', 451),
  ('spiritual', '45', '5 YEARS (Age 45)', 'Faith in Family Life:', 'Faith guiding every major decision — career, family, finances', 452),
  ('spiritual', '45', '5 YEARS (Age 45)', 'Faith & Giving:', 'Identify and begin funding a Catholic school or parish initiative', 453),
  ('spiritual', '45', '5 YEARS (Age 45)', 'Faith & Giving:', 'Faith-based giving a meaningful percentage of income', 454),
  ('spiritual', '45', '5 YEARS (Age 45)', 'Spiritual Milestones:', 'Camino de Santiago — walk the historic 500-mile pilgrimage route across Spain', 455),
  ('spiritual', '45', '5 YEARS (Age 45)', 'Spiritual Milestones:', 'Annual spiritual retreat maintained (non-negotiable)', 456),
  ('spiritual', '45', '5 YEARS (Age 45)', 'Spiritual Milestones:', 'Known as a leader whose faith-shaped values are visible in how he operates', 457),
  ('spiritual', '50', '10 YEARS (Age 50)', 'Church & Community:', 'Deeply rooted parish member — trusted, possibly in a leadership or stewardship role', 458),
  ('spiritual', '50', '10 YEARS (Age 50)', 'Church & Community:', 'Visible servant leader in the parish', 459),
  ('spiritual', '50', '10 YEARS (Age 50)', 'Church & Community:', 'Possibly mentoring younger members of the community', 460),
  ('spiritual', '50', '10 YEARS (Age 50)', 'Faith in Family & Leadership:', 'Public about faith as a grounding force in life and leadership', 461),
  ('spiritual', '50', '10 YEARS (Age 50)', 'Faith in Family & Leadership:', 'Kids (ages 5–12) grounded in Catholic faith — attending Catholic school', 462),
  ('spiritual', '50', '10 YEARS (Age 50)', 'Faith in Family & Leadership:', 'Speaking openly about faith''s role in my career and decisions', 463),
  ('spiritual', '50', '10 YEARS (Age 50)', 'Faith & Giving:', 'Meaningful donor to Catholic education', 464),
  ('spiritual', '50', '10 YEARS (Age 50)', 'Faith & Giving:', 'Supporting families who cannot afford Catholic school', 465),
  ('spiritual', '50', '10 YEARS (Age 50)', 'Faith & Giving:', 'Active in faith-based philanthropic giving', 466),
  ('spiritual', '50', '10 YEARS (Age 50)', 'Spiritual Milestones:', 'Pilgrimage to Rome and the Vatican — walking where Peter walked (Target: Age 47–50)', 467),
  ('spiritual', '50', '10 YEARS (Age 50)', 'Spiritual Milestones:', 'Annual spiritual retreat maintained', 468),
  ('spiritual', '50', '10 YEARS (Age 50)', 'Spiritual Milestones:', 'Spiritual maturity — faith steady under pressure, in success, and in grief', 469),
  ('spiritual', '60', '20 YEARS (Age 60)', 'Church & Legacy:', 'A church community that has shaped me and that I have shaped — legacy of presence', 470),
  ('spiritual', '60', '20 YEARS (Age 60)', 'Church & Legacy:', 'Legacy of service; faith expressed through action over decades', 471),
  ('spiritual', '60', '20 YEARS (Age 60)', 'Church & Legacy:', 'Patriarch of a faith-filled family — the through-line of everything built', 472),
  ('spiritual', '60', '20 YEARS (Age 60)', 'Faith in Leadership & Life:', 'A legacy of servant leadership rooted in faith', 473),
  ('spiritual', '60', '20 YEARS (Age 60)', 'Faith in Leadership & Life:', 'Known as a man of deep, quiet, tested faith — the kind that endures everything', 474),
  ('spiritual', '60', '20 YEARS (Age 60)', 'Faith in Leadership & Life:', 'Faith the answer to why I did everything I did', 475),
  ('spiritual', '60', '20 YEARS (Age 60)', 'Faith & Giving:', 'Legacy gift — funding a scholarship, a building, or a program in the family''s name', 476),
  ('spiritual', '60', '20 YEARS (Age 60)', 'Faith & Giving:', 'Possible endowed scholarship at a Catholic institution', 477),
  ('spiritual', '60', '20 YEARS (Age 60)', 'Faith & Giving:', '$500K–$1M+ in faith-based philanthropic giving over lifetime', 478),
  ('spiritual', '60', '20 YEARS (Age 60)', 'Spiritual Milestones:', 'Pilgrimage to the Holy Land & Jerusalem — the journey of a lifetime (Target: Age 50–55)', 479),
  ('spiritual', '60', '20 YEARS (Age 60)', 'Spiritual Milestones:', 'Walking where Jesus walked — Sea of Galilee, Gethsemane, Via Dolorosa', 480),
  ('spiritual', '60', '20 YEARS (Age 60)', 'Spiritual Milestones:', 'A man at peace — wisdom from a full life, faith intact, legacy secure', 481);

-- Total: 481 goals seeded
